#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class KubeCluster_ArgSpec:
    argument_spec = {'appGroups': {'elements': 'dict',
                                   'options': {'applications': {'elements': 'dict',
                                                                'options': {'config': {'type': 'str'},
                                                                            'enabled': {'default': True,
                                                                                        'type': 'bool'},
                                                                            'excludeListSnippets': {'elements': 'dict',
                                                                                                    'options': {'disabled': {'default': False,
                                                                                                                             'type': 'bool'},
                                                                                                                'excludeList': {'type': 'list'},
                                                                                                                'modeFull': {'default': False,
                                                                                                                             'type': 'bool'},
                                                                                                                'modeGrab': {'default': False,
                                                                                                                             'type': 'bool'},
                                                                                                                'modeGrabNew': {'default': False,
                                                                                                                                'type': 'bool'},
                                                                                                                'modeSync': {'default': True,
                                                                                                                             'type': 'bool'},
                                                                                                                'modeUpdate': {'default': True,
                                                                                                                               'type': 'bool'},
                                                                                                                'name': {'required': True,
                                                                                                                         'type': 'str'},
                                                                                                                'noNewFiles': {'default': False,
                                                                                                                               'type': 'bool'}},
                                                                                                    'type': 'list'},
                                                                            'extraEnvironment': {'elements': 'dict',
                                                                                                 'options': {'name': {'required': True,
                                                                                                                      'type': 'str'},
                                                                                                             'nodesEnvironment': {'default': False,
                                                                                                                                  'type': 'bool'},
                                                                                                             'value': {'type': 'str'}},
                                                                                                 'type': 'list'},
                                                                            'format': {'choices': ['Yaml',
                                                                                                   'Json',
                                                                                                   'Other'],
                                                                                       'default': 'Yaml',
                                                                                       'type': 'str'},
                                                                            'name': {'required': True,
                                                                                     'type': 'str'},
                                                                            'state': {'default': 0,
                                                                                      'type': 'int'}},
                                                                'type': 'list'},
                                               'enabled': {'default': True, 'type': 'bool'},
                                               'name': {'required': True, 'type': 'str'}},
                                   'type': 'list'},
                     'capiNamespace': {'default': 'default', 'type': 'str'},
                     'capiTemplate': {'default': False, 'type': 'bool'},
                     'cloneFrom': {'default': '', 'type': 'str'},
                     'etcdCluster': {'type': 'str'},
                     'external': {'default': False, 'type': 'bool'},
                     'externalIngressServer': {'type': 'str'},
                     'externalPort': {'default': 0, 'type': 'int'},
                     'ingressProxyBackendPort': {'default': 0, 'type': 'int'},
                     'ingressProxyEnable': {'default': False, 'type': 'bool'},
                     'ingressProxyListenPort': {'default': 443, 'type': 'int'},
                     'internalNetwork': {'type': 'str'},
                     'kubeCluster': {'type': 'str'},
                     'kubeDnsIp': {'default': '0.0.0.0', 'type': 'str'},
                     'kubeadm_ca_cert': {'type': 'str'},
                     'kubeadm_ca_key': {'type': 'str'},
                     'kubeadm_init_cert_key': {'type': 'str'},
                     'kubeadm_init_file': {'type': 'str'},
                     'kubernetesApiServer': {'type': 'str'},
                     'kubernetesApiServerProxyPort': {'default': 6444, 'type': 'int'},
                     'labelSets': {'elements': 'dict',
                                   'options': {'categories': {'type': 'list'},
                                               'labels': {'type': 'list'},
                                               'name': {'required': True, 'type': 'str'},
                                               'nodes': {'type': 'list'},
                                               'overlays': {'type': 'list'}},
                                   'type': 'list'},
                     'moduleFileTemplate': {'type': 'str'},
                     'name': {'required': True, 'type': 'str'},
                     'notes': {'type': 'str'},
                     'options': {'type': 'json'},
                     'podNetwork': {'type': 'str'},
                     'podNetworkNodeMask': {'type': 'str'},
                     'serviceNetwork': {'type': 'str'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'trustedDomains': {'default': ['kubernetes',
                                                    'kubernetes.default',
                                                    'kubernetes.default.svc',
                                                    'master',
                                                    'localhost'],
                                        'type': 'list'},
                     'users': {'elements': 'dict',
                               'options': {'initialDefaultNamespace': {'type': 'str'},
                                           'manageKubeConfig': {'default': True, 'type': 'bool'},
                                           'userName': {'required': True, 'type': 'str'}},
                               'type': 'list'},
                     'version': {'type': 'str'}}