#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class PowerDistributionUnit_ArgSpec:
    argument_spec = {'accessSettings': {'options': {'password': {'no_log': True, 'type': 'str'},
                                                    'rest_port': {'default': 8765, 'type': 'int'},
                                                    'updateInNV': {'default': False,
                                                                   'type': 'bool'},
                                                    'updateInZtp': {'default': False,
                                                                    'type': 'bool'},
                                                    'username': {'type': 'str'}},
                                        'type': 'dict'},
                     'bmcSettings': {'options': {'extraArguments': {'type': 'str'},
                                                 'firmwareManageMode': {'choices': ['NONE',
                                                                                    'AUTO',
                                                                                    'ILO',
                                                                                    'H100',
                                                                                    'B200',
                                                                                    'GB200',
                                                                                    'GB200SW',
                                                                                    'B300',
                                                                                    'GB300',
                                                                                    'GB300SW'],
                                                                        'default': 'AUTO',
                                                                        'type': 'str'},
                                                 'leakPolicy': {'choices': ['NONE',
                                                                            'ENABLED',
                                                                            'DISABLED'],
                                                                'default': 'NONE',
                                                                'type': 'str'},
                                                 'leakReactionDelay': {'default': 0.0,
                                                                       'type': 'float'},
                                                 'password': {'no_log': True, 'type': 'str'},
                                                 'powerResetDelay': {'default': 0, 'type': 'int'},
                                                 'privilege': {'choices': ['CALLBACK',
                                                                           'USER',
                                                                           'OPERATOR',
                                                                           'ADMINISTRATOR',
                                                                           'OEM_PROPRIETARY',
                                                                           'NO_ACCESS'],
                                                               'default': 'ADMINISTRATOR',
                                                               'type': 'str'},
                                                 'userID': {'default': -1, 'type': 'int'},
                                                 'userName': {'type': 'str'}},
                                     'type': 'dict'},
                     'chassisPosition': {'options': {'chassis': {'type': 'str'},
                                                     'position': {'default': 1, 'type': 'int'},
                                                     'slot': {'type': 'str'},
                                                     'width': {'default': 1, 'type': 'int'}},
                                         'type': 'dict'},
                     'cloneFrom': {'default': '', 'type': 'str'},
                     'controlScript': {'type': 'str'},
                     'controlScriptTimeout': {'default': 5, 'type': 'int'},
                     'customPingScript': {'type': 'str'},
                     'customPingScriptArgument': {'type': 'str'},
                     'customPowerScript': {'type': 'str'},
                     'customPowerScriptArgument': {'type': 'str'},
                     'defaultGateway': {'default': '0.0.0.0', 'type': 'str'},
                     'defaultGatewayMetric': {'default': 0, 'type': 'int'},
                     'disableSNMP': {'default': False, 'type': 'bool'},
                     'extra_values': {'type': 'json'},
                     'hostname': {'required': True, 'type': 'str'},
                     'interfaces_NetworkAliasInterface': {'elements': 'dict',
                                                          'options': {'additionalHostnames': {'type': 'list'},
                                                                      'alternativeHostname': {'type': 'str'},
                                                                      'bootable': {'default': False,
                                                                                   'type': 'bool'},
                                                                      'bringupduringinstall': {'choices': ['NO',
                                                                                                           'YES',
                                                                                                           'YESANDKEEP'],
                                                                                               'default': 'NO',
                                                                                               'type': 'str'},
                                                                      'connectedMode': {'default': False,
                                                                                        'type': 'bool'},
                                                                      'dhcp': {'default': False,
                                                                               'type': 'bool'},
                                                                      'excludeFromDhcpd': {'default': False,
                                                                                           'type': 'bool'},
                                                                      'extra_values': {'type': 'json'},
                                                                      'ip': {'default': '0.0.0.0',
                                                                             'type': 'str'},
                                                                      'ipv6Dhcp': {'default': False,
                                                                                   'type': 'bool'},
                                                                      'ipv6Ip': {'default': '::0',
                                                                                 'type': 'str'},
                                                                      'name': {'required': True,
                                                                               'type': 'str'},
                                                                      'network': {'type': 'str'},
                                                                      'onNetworkPriority': {'default': 40,
                                                                                            'type': 'int'},
                                                                      'startIf': {'choices': ['ALWAYS',
                                                                                              'ACTIVE',
                                                                                              'PASSIVE',
                                                                                              'PREFERPASSIVE'],
                                                                                  'default': 'ALWAYS',
                                                                                  'type': 'str'},
                                                                      'switchPorts': {'elements': 'dict',
                                                                                      'options': {'breakout': {'default': -1,
                                                                                                               'type': 'int'},
                                                                                                  'networkSwitch': {'type': 'str'},
                                                                                                  'port': {'default': 0,
                                                                                                           'type': 'int'}},
                                                                                      'type': 'list'}},
                                                          'type': 'list'},
                     'interfaces_NetworkBmcInterface': {'elements': 'dict',
                                                        'options': {'additionalHostnames': {'type': 'list'},
                                                                    'alternativeHostname': {'type': 'str'},
                                                                    'bootable': {'default': False,
                                                                                 'type': 'bool'},
                                                                    'bringupduringinstall': {'choices': ['NO',
                                                                                                         'YES',
                                                                                                         'YESANDKEEP'],
                                                                                             'default': 'NO',
                                                                                             'type': 'str'},
                                                                    'connectedMode': {'default': False,
                                                                                      'type': 'bool'},
                                                                    'dhcp': {'default': False,
                                                                             'type': 'bool'},
                                                                    'excludeFromDhcpd': {'default': False,
                                                                                         'type': 'bool'},
                                                                    'extra_values': {'type': 'json'},
                                                                    'gateway': {'default': '0.0.0.0',
                                                                                'type': 'str'},
                                                                    'ip': {'default': '0.0.0.0',
                                                                           'type': 'str'},
                                                                    'ipv6Dhcp': {'default': False,
                                                                                 'type': 'bool'},
                                                                    'ipv6Ip': {'default': '::0',
                                                                               'type': 'str'},
                                                                    'lanchannel': {'default': 1,
                                                                                   'type': 'int'},
                                                                    'mac': {'default': '00:00:00:00:00:00',
                                                                            'type': 'str'},
                                                                    'name': {'required': True,
                                                                             'type': 'str'},
                                                                    'network': {'type': 'str'},
                                                                    'onNetworkPriority': {'default': 10,
                                                                                          'type': 'int'},
                                                                    'startIf': {'choices': ['ALWAYS',
                                                                                            'ACTIVE',
                                                                                            'PASSIVE',
                                                                                            'PREFERPASSIVE'],
                                                                                'default': 'ALWAYS',
                                                                                'type': 'str'},
                                                                    'switchPorts': {'elements': 'dict',
                                                                                    'options': {'breakout': {'default': -1,
                                                                                                             'type': 'int'},
                                                                                                'networkSwitch': {'type': 'str'},
                                                                                                'port': {'default': 0,
                                                                                                         'type': 'int'}},
                                                                                    'type': 'list'},
                                                                    'vlanid': {'default': 0,
                                                                               'type': 'int'}},
                                                        'type': 'list'},
                     'interfaces_NetworkBondInterface': {'elements': 'dict',
                                                         'options': {'additionalHostnames': {'type': 'list'},
                                                                     'alternativeHostname': {'type': 'str'},
                                                                     'bootable': {'default': False,
                                                                                  'type': 'bool'},
                                                                     'bringupduringinstall': {'choices': ['NO',
                                                                                                          'YES',
                                                                                                          'YESANDKEEP'],
                                                                                              'default': 'NO',
                                                                                              'type': 'str'},
                                                                     'connectedMode': {'default': False,
                                                                                       'type': 'bool'},
                                                                     'dhcp': {'default': False,
                                                                              'type': 'bool'},
                                                                     'excludeFromDhcpd': {'default': False,
                                                                                          'type': 'bool'},
                                                                     'extra_values': {'type': 'json'},
                                                                     'interfaces': {'type': 'list'},
                                                                     'ip': {'default': '0.0.0.0',
                                                                            'type': 'str'},
                                                                     'ipv6Dhcp': {'default': False,
                                                                                  'type': 'bool'},
                                                                     'ipv6Ip': {'default': '::0',
                                                                                'type': 'str'},
                                                                     'mac': {'default': '00:00:00:00:00:00',
                                                                             'type': 'str'},
                                                                     'mode': {'default': 0,
                                                                              'type': 'int'},
                                                                     'name': {'required': True,
                                                                              'type': 'str'},
                                                                     'network': {'type': 'str'},
                                                                     'onNetworkPriority': {'default': 70,
                                                                                           'type': 'int'},
                                                                     'options': {'type': 'str'},
                                                                     'startIf': {'choices': ['ALWAYS',
                                                                                             'ACTIVE',
                                                                                             'PASSIVE',
                                                                                             'PREFERPASSIVE'],
                                                                                 'default': 'ALWAYS',
                                                                                 'type': 'str'},
                                                                     'switchPorts': {'elements': 'dict',
                                                                                     'options': {'breakout': {'default': -1,
                                                                                                              'type': 'int'},
                                                                                                 'networkSwitch': {'type': 'str'},
                                                                                                 'port': {'default': 0,
                                                                                                          'type': 'int'}},
                                                                                     'type': 'list'}},
                                                         'type': 'list'},
                     'interfaces_NetworkBridgeInterface': {'elements': 'dict',
                                                           'options': {'additionalHostnames': {'type': 'list'},
                                                                       'alternativeHostname': {'type': 'str'},
                                                                       'bootable': {'default': False,
                                                                                    'type': 'bool'},
                                                                       'bringupduringinstall': {'choices': ['NO',
                                                                                                            'YES',
                                                                                                            'YESANDKEEP'],
                                                                                                'default': 'NO',
                                                                                                'type': 'str'},
                                                                       'connectedMode': {'default': False,
                                                                                         'type': 'bool'},
                                                                       'dhcp': {'default': False,
                                                                                'type': 'bool'},
                                                                       'excludeFromDhcpd': {'default': False,
                                                                                            'type': 'bool'},
                                                                       'extra_values': {'type': 'json'},
                                                                       'forward_delay': {'default': 15,
                                                                                         'type': 'int'},
                                                                       'interfaces': {'type': 'list'},
                                                                       'ip': {'default': '0.0.0.0',
                                                                              'type': 'str'},
                                                                       'ipv6Dhcp': {'default': False,
                                                                                    'type': 'bool'},
                                                                       'ipv6Ip': {'default': '::0',
                                                                                  'type': 'str'},
                                                                       'name': {'required': True,
                                                                                'type': 'str'},
                                                                       'network': {'type': 'str'},
                                                                       'onNetworkPriority': {'default': 80,
                                                                                             'type': 'int'},
                                                                       'startIf': {'choices': ['ALWAYS',
                                                                                               'ACTIVE',
                                                                                               'PASSIVE',
                                                                                               'PREFERPASSIVE'],
                                                                                   'default': 'ALWAYS',
                                                                                   'type': 'str'},
                                                                       'stp': {'default': False,
                                                                               'type': 'bool'},
                                                                       'switchPorts': {'elements': 'dict',
                                                                                       'options': {'breakout': {'default': -1,
                                                                                                                'type': 'int'},
                                                                                                   'networkSwitch': {'type': 'str'},
                                                                                                   'port': {'default': 0,
                                                                                                            'type': 'int'}},
                                                                                       'type': 'list'}},
                                                           'type': 'list'},
                     'interfaces_NetworkNetMapInterface': {'elements': 'dict',
                                                           'options': {'additionalHostnames': {'type': 'list'},
                                                                       'alternativeHostname': {'type': 'str'},
                                                                       'bootable': {'default': False,
                                                                                    'type': 'bool'},
                                                                       'bringupduringinstall': {'choices': ['NO',
                                                                                                            'YES',
                                                                                                            'YESANDKEEP'],
                                                                                                'default': 'NO',
                                                                                                'type': 'str'},
                                                                       'connectedMode': {'default': False,
                                                                                         'type': 'bool'},
                                                                       'dhcp': {'default': False,
                                                                                'type': 'bool'},
                                                                       'excludeFromDhcpd': {'default': False,
                                                                                            'type': 'bool'},
                                                                       'extra_values': {'type': 'json'},
                                                                       'ip': {'default': '0.0.0.0',
                                                                              'type': 'str'},
                                                                       'ipv6Dhcp': {'default': False,
                                                                                    'type': 'bool'},
                                                                       'ipv6Ip': {'default': '::0',
                                                                                  'type': 'str'},
                                                                       'name': {'required': True,
                                                                                'type': 'str'},
                                                                       'network': {'type': 'str'},
                                                                       'onNetworkPriority': {'default': 20,
                                                                                             'type': 'int'},
                                                                       'startIf': {'choices': ['ALWAYS',
                                                                                               'ACTIVE',
                                                                                               'PASSIVE',
                                                                                               'PREFERPASSIVE'],
                                                                                   'default': 'ALWAYS',
                                                                                   'type': 'str'},
                                                                       'switchPorts': {'elements': 'dict',
                                                                                       'options': {'breakout': {'default': -1,
                                                                                                                'type': 'int'},
                                                                                                   'networkSwitch': {'type': 'str'},
                                                                                                   'port': {'default': 0,
                                                                                                            'type': 'int'}},
                                                                                       'type': 'list'}},
                                                           'type': 'list'},
                     'interfaces_NetworkPhysicalInterface': {'elements': 'dict',
                                                             'options': {'additionalHostnames': {'type': 'list'},
                                                                         'alternativeHostname': {'type': 'str'},
                                                                         'bootable': {'default': False,
                                                                                      'type': 'bool'},
                                                                         'bringupduringinstall': {'choices': ['NO',
                                                                                                              'YES',
                                                                                                              'YESANDKEEP'],
                                                                                                  'default': 'NO',
                                                                                                  'type': 'str'},
                                                                         'cardtype': {'type': 'str'},
                                                                         'connectedMode': {'default': False,
                                                                                           'type': 'bool'},
                                                                         'dhcp': {'default': False,
                                                                                  'type': 'bool'},
                                                                         'excludeFromDhcpd': {'default': False,
                                                                                              'type': 'bool'},
                                                                         'extra_values': {'type': 'json'},
                                                                         'ip': {'default': '0.0.0.0',
                                                                                'type': 'str'},
                                                                         'ipv6Dhcp': {'default': False,
                                                                                      'type': 'bool'},
                                                                         'ipv6Ip': {'default': '::0',
                                                                                    'type': 'str'},
                                                                         'mac': {'default': '00:00:00:00:00:00',
                                                                                 'type': 'str'},
                                                                         'name': {'required': True,
                                                                                  'type': 'str'},
                                                                         'network': {'type': 'str'},
                                                                         'onNetworkPriority': {'default': 60,
                                                                                               'type': 'int'},
                                                                         'speed': {'type': 'str'},
                                                                         'startIf': {'choices': ['ALWAYS',
                                                                                                 'ACTIVE',
                                                                                                 'PASSIVE',
                                                                                                 'PREFERPASSIVE'],
                                                                                     'default': 'ALWAYS',
                                                                                     'type': 'str'},
                                                                         'switchPorts': {'elements': 'dict',
                                                                                         'options': {'breakout': {'default': -1,
                                                                                                                  'type': 'int'},
                                                                                                     'networkSwitch': {'type': 'str'},
                                                                                                     'port': {'default': 0,
                                                                                                              'type': 'int'}},
                                                                                         'type': 'list'}},
                                                             'type': 'list'},
                     'interfaces_NetworkTunnelInterface': {'elements': 'dict',
                                                           'options': {'additionalHostnames': {'type': 'list'},
                                                                       'alternativeHostname': {'type': 'str'},
                                                                       'bootable': {'default': False,
                                                                                    'type': 'bool'},
                                                                       'bringupduringinstall': {'choices': ['NO',
                                                                                                            'YES',
                                                                                                            'YESANDKEEP'],
                                                                                                'default': 'NO',
                                                                                                'type': 'str'},
                                                                       'connectedMode': {'default': False,
                                                                                         'type': 'bool'},
                                                                       'dhcp': {'default': False,
                                                                                'type': 'bool'},
                                                                       'excludeFromDhcpd': {'default': False,
                                                                                            'type': 'bool'},
                                                                       'extra_values': {'type': 'json'},
                                                                       'ip': {'default': '0.0.0.0',
                                                                              'type': 'str'},
                                                                       'ipv6Dhcp': {'default': False,
                                                                                    'type': 'bool'},
                                                                       'ipv6Ip': {'default': '::0',
                                                                                  'type': 'str'},
                                                                       'name': {'required': True,
                                                                                'type': 'str'},
                                                                       'network': {'type': 'str'},
                                                                       'onNetworkPriority': {'default': 30,
                                                                                             'type': 'int'},
                                                                       'startIf': {'choices': ['ALWAYS',
                                                                                               'ACTIVE',
                                                                                               'PASSIVE',
                                                                                               'PREFERPASSIVE'],
                                                                                   'default': 'ALWAYS',
                                                                                   'type': 'str'},
                                                                       'switchPorts': {'elements': 'dict',
                                                                                       'options': {'breakout': {'default': -1,
                                                                                                                'type': 'int'},
                                                                                                   'networkSwitch': {'type': 'str'},
                                                                                                   'port': {'default': 0,
                                                                                                            'type': 'int'}},
                                                                                       'type': 'list'}},
                                                           'type': 'list'},
                     'interfaces_NetworkVLANInterface': {'elements': 'dict',
                                                         'options': {'additionalHostnames': {'type': 'list'},
                                                                     'alternativeHostname': {'type': 'str'},
                                                                     'bootable': {'default': False,
                                                                                  'type': 'bool'},
                                                                     'bringupduringinstall': {'choices': ['NO',
                                                                                                          'YES',
                                                                                                          'YESANDKEEP'],
                                                                                              'default': 'NO',
                                                                                              'type': 'str'},
                                                                     'connectedMode': {'default': False,
                                                                                       'type': 'bool'},
                                                                     'dhcp': {'default': False,
                                                                              'type': 'bool'},
                                                                     'excludeFromDhcpd': {'default': False,
                                                                                          'type': 'bool'},
                                                                     'extra_values': {'type': 'json'},
                                                                     'ip': {'default': '0.0.0.0',
                                                                            'type': 'str'},
                                                                     'ipv6Dhcp': {'default': False,
                                                                                  'type': 'bool'},
                                                                     'ipv6Ip': {'default': '::0',
                                                                                'type': 'str'},
                                                                     'name': {'required': True,
                                                                              'type': 'str'},
                                                                     'network': {'type': 'str'},
                                                                     'onNetworkPriority': {'default': 50,
                                                                                           'type': 'int'},
                                                                     'reorder_hdr': {'default': True,
                                                                                     'type': 'bool'},
                                                                     'startIf': {'choices': ['ALWAYS',
                                                                                             'ACTIVE',
                                                                                             'PASSIVE',
                                                                                             'PREFERPASSIVE'],
                                                                                 'default': 'ALWAYS',
                                                                                 'type': 'str'},
                                                                     'switchPorts': {'elements': 'dict',
                                                                                     'options': {'breakout': {'default': -1,
                                                                                                              'type': 'int'},
                                                                                                 'networkSwitch': {'type': 'str'},
                                                                                                 'port': {'default': 0,
                                                                                                          'type': 'int'}},
                                                                                     'type': 'list'}},
                                                         'type': 'list'},
                     'mac': {'default': '00:00:00:00:00:00', 'type': 'str'},
                     'managementNetwork': {'type': 'str'},
                     'notes': {'type': 'str'},
                     'partNumber': {'type': 'str'},
                     'partition': {'type': 'str'},
                     'powerControl': {'default': 'none', 'type': 'str'},
                     'powerDistributionUnits': {'elements': 'dict',
                                                'options': {'pdu': {'type': 'str'},
                                                            'port': {'default': 0, 'type': 'int'}},
                                                'type': 'list'},
                     'prometheusMetricForwarders': {'elements': 'dict',
                                                    'options': {'caPath': {'type': 'str'},
                                                                'certificatePath': {'type': 'str'},
                                                                'method': {'choices': ['POST',
                                                                                       'GET'],
                                                                           'default': 'POST',
                                                                           'type': 'str'},
                                                                'name': {'required': True,
                                                                         'type': 'str'},
                                                                'password': {'no_log': True,
                                                                             'type': 'str'},
                                                                'privateKeyPath': {'type': 'str'},
                                                                'timeout': {'default': 5,
                                                                            'type': 'int'},
                                                                'urls': {'type': 'list'},
                                                                'username': {'type': 'str'}},
                                                    'type': 'list'},
                     'provisioningInterface': {'type': 'str'},
                     'rackPosition': {'options': {'height': {'default': 1, 'type': 'int'},
                                                  'position': {'default': 1, 'type': 'int'},
                                                  'rack': {'type': 'str'},
                                                  'trayId': {'type': 'str'},
                                                  'trayName': {'type': 'str'}},
                                      'type': 'dict'},
                     'serialNumber': {'type': 'str'},
                     'snmpSettings': {'options': {'authKey': {'type': 'str'},
                                                  'authProtocol': {'choices': ['MD5', 'SHA'],
                                                                   'default': 'MD5',
                                                                   'type': 'str'},
                                                  'context': {'type': 'str'},
                                                  'extra_values': {'type': 'json'},
                                                  'filename': {'type': 'str'},
                                                  'privKey': {'type': 'str'},
                                                  'privProtocol': {'choices': ['AES', 'DES'],
                                                                   'default': 'DES',
                                                                   'type': 'str'},
                                                  'readString': {'default': 'public',
                                                                 'type': 'str'},
                                                  'retries': {'default': -1, 'type': 'int'},
                                                  'securityLevel': {'choices': ['noAuthNoPriv',
                                                                                'authNoPriv',
                                                                                'authPriv'],
                                                                    'default': 'authPriv',
                                                                    'type': 'str'},
                                                  'securityName': {'type': 'str'},
                                                  'timeout': {'default': 0.0, 'type': 'float'},
                                                  'version': {'choices': ['V1',
                                                                          'V2c',
                                                                          'V3',
                                                                          'File'],
                                                              'default': 'V2c',
                                                              'type': 'str'},
                                                  'vlanTimeout': {'default': 0.0, 'type': 'float'},
                                                  'writeString': {'default': 'private',
                                                                  'type': 'str'}},
                                      'type': 'dict'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'supportsGNSS': {'default': False, 'type': 'bool'},
                     'switchPorts': {'elements': 'dict',
                                     'options': {'breakout': {'default': -1, 'type': 'int'},
                                                 'networkSwitch': {'type': 'str'},
                                                 'port': {'default': 0, 'type': 'int'}},
                                     'type': 'list'},
                     'userDefinedResources': {'type': 'list'},
                     'userdefined1': {'type': 'str'},
                     'userdefined2': {'type': 'str'}}