---
- name: Gather distro specific facts
  setup:
    gather_subset: "!all,!min,os_family"

- name: Include distro specific variables
  include_vars:
    file: vars/{{ ansible_os_family }}.yml

- name: Ensure Port configuration exists in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port (\d+)$'
    line: 'Port \1'
    backrefs: true
    state: present
  notify:
    - Restart ssh

# not supported on c8u4,s12sp5,s15sp2,rhel8u4
# - name: Ensure /etc/ssh/sshd_config.d directory exists
#   file:
#     path: /etc/ssh/sshd_config.d
#     state: directory
#     owner: root
#     group: root
#     mode: 0755

# - name: Ensure 'Include /etc/ssh/sshd_config.d/brightcomputing.bcm.software_image_tunnel.*' exists in /etc/ssh/sshd_config
#   lineinfile:
#     path: /etc/ssh/sshd_config
#     line: Include /etc/ssh/sshd_config.d/brightcomputing.bcm.software_image_tunnel.*
#     state: present
#   notify:
#     - Restart ssh

- import_tasks: "{{ software_image_tunnels_action | default('open') }}-tunnels.yml"
