---
namespace: fabiendupont
name: bcm
version: 0.1.0
readme: README.md
authors:
  - Fabien Dupont <fdupont@redhat.com>

description: Community-driven Ansible collection for high-level automation on NVIDIA Base Command Manager (BCM). Not officially supported by NVIDIA.

license:
  - GPL-3.0-or-later

tags:
  - nvidia
  - bcm
  - base_command_manager
  - cluster
  - hpc
  - infrastructure

dependencies:
  brightcomputing.bcm110: '>=30.0.0'
  containers.podman: '>=1.10.0'

repository: https://github.com/fabiendupont/nvidia-bcm-ansible
documentation: https://github.com/fabiendupont/nvidia-bcm-ansible
homepage: https://github.com/fabiendupont/nvidia-bcm-ansible
issues: https://github.com/fabiendupont/nvidia-bcm-ansible/issues

build_ignore:
  - bcm-headnode
  - "*.tar.gz"
  - .git
  - .github
  - tests/output
  - .pytest_cache
  - __pycache__
  - "*.pyc"
  - .vscode
  - .idea
  - collections
  - tmp
  - "*.log"
  - .ansible
  - .claude
  - .venv
  - .envrc
  - .bcm
  - lib
