---
# Ansible Galaxy requirements file for BCM Ansible Collection
#
# Usage:
#   ansible-galaxy collection install -r requirements.yml

collections:
  # External dependencies
  - name: ansible.posix
    version: '>=1.5.0'

  - name: containers.podman
    version: '>=1.10.0'

  # Install the BCM collection from local tarball
  - name: /root/bcm/ansible_collections/fabiendupont/bcm/fabiendupont-bcm-1.0.0.tar.gz
    type: file

  # Or from a URL (if hosted)
  # - name: https://releases.example.com/fabiendupont-bcm-1.0.0.tar.gz
  #   type: url

  # Or from source directory
  # - name: /root/bcm/ansible_collections/fabiendupont/bcm
  #   type: dir
