#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class FSPart_ArgSpec:
    argument_spec = {'abortOnPreSyncScriptFailure': {'default': True, 'type': 'bool'},
                     'autoDirtyDelay': {'default': 0, 'type': 'int'},
                     'cloneFrom': {'default': '', 'type': 'str'},
                     'dirtyAutoSyncDelay': {'default': 0, 'type': 'int'},
                     'excludeListSnippets': {'elements': 'dict',
                                             'options': {'disabled': {'default': False,
                                                                      'type': 'bool'},
                                                         'excludeList': {'type': 'list'},
                                                         'modeFull': {'default': False,
                                                                      'type': 'bool'},
                                                         'modeGrab': {'default': False,
                                                                      'type': 'bool'},
                                                         'modeGrabNew': {'default': False,
                                                                         'type': 'bool'},
                                                         'modeSync': {'default': True,
                                                                      'type': 'bool'},
                                                         'modeUpdate': {'default': True,
                                                                        'type': 'bool'},
                                                         'name': {'required': True, 'type': 'str'},
                                                         'noNewFiles': {'default': False,
                                                                        'type': 'bool'}},
                                             'type': 'list'},
                     'extraRsyncArguments': {'type': 'list'},
                     'path': {'required': True, 'type': 'str'},
                     'postSyncScript': {'type': 'str'},
                     'preSyncScript': {'type': 'str'},
                     'rsyncAcls': {'default': True, 'type': 'bool'},
                     'rsyncBandWidthLimit': {'default': 0, 'type': 'int'},
                     'rsyncBlockSize': {'default': 0, 'type': 'int'},
                     'rsyncCheckNetworkMount': {'default': True, 'type': 'bool'},
                     'rsyncCompress': {'choices': ['NEVER',
                                                   'ALWAYS',
                                                   'WHEN_SSH',
                                                   'WHEN_TUNNEL',
                                                   'WHEN_SSH_OR_TUNNEL'],
                                       'default': 'NEVER',
                                       'type': 'str'},
                     'rsyncCompressLevel': {'choices': ['NONE', 'FAST', 'DEFAULT', 'BEST', 'SSH'],
                                            'default': 'DEFAULT',
                                            'type': 'str'},
                     'rsyncDelta': {'default': False, 'type': 'bool'},
                     'rsyncForce': {'default': True, 'type': 'bool'},
                     'rsyncHardlinks': {'default': True, 'type': 'bool'},
                     'rsyncNumericIds': {'default': True, 'type': 'bool'},
                     'rsyncPrune': {'default': False, 'type': 'bool'},
                     'rsyncSparse': {'default': True, 'type': 'bool'},
                     'rsyncXattrs': {'default': True, 'type': 'bool'},
                     'runPostOnFailure': {'default': False, 'type': 'bool'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'syncScriptTimeout': {'default': 15, 'type': 'int'},
                     'type': {'choices': ['IMAGE',
                                          'BOOT',
                                          'CM_SHARED',
                                          'CM_NODE_INSTALLER',
                                          'TFTPBOOT',
                                          'CUSTOM'],
                              'default': 'CUSTOM',
                              'type': 'str'},
                     'watchDirectories': {'type': 'list'}}