#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class MonitoringTrigger_ArgSpec:
    argument_spec = {'cloneFrom': {'default': '', 'type': 'str'},
                     'disabled': {'default': False, 'type': 'bool'},
                     'duringActions': {'type': 'list'},
                     'enterActions': {'type': 'list'},
                     'expression_MonitoringCompareExpression': {'options': {'code': {'type': 'str'},
                                                                            'entities': {'type': 'str'},
                                                                            'grouping': {'choices': ['ANY',
                                                                                                     'ALL',
                                                                                                     'SUM',
                                                                                                     'MIN',
                                                                                                     'MAX',
                                                                                                     'AVG'],
                                                                                         'default': 'ANY',
                                                                                         'type': 'str'},
                                                                            'measurables': {'type': 'str'},
                                                                            'name': {'required': True,
                                                                                     'type': 'str'},
                                                                            'op': {'choices': ['EQ',
                                                                                               'NE',
                                                                                               'LT',
                                                                                               'GT'],
                                                                                   'default': 'EQ',
                                                                                   'type': 'str'},
                                                                            'parameters': {'type': 'str'},
                                                                            'useRaw': {'default': False,
                                                                                       'type': 'bool'},
                                                                            'value': {'default': 'FAIL',
                                                                                      'type': 'str'}},
                                                                'type': 'dict'},
                     'expression_MonitoringGroupedExpression': {'options': {'allowMissing': {'default': False,
                                                                                             'type': 'bool'},
                                                                            'expressions': {'elements': 'dict',
                                                                                            'options': {'code': {'type': 'str'},
                                                                                                        'entities': {'type': 'str'},
                                                                                                        'grouping': {'choices': ['ANY',
                                                                                                                                 'ALL',
                                                                                                                                 'SUM',
                                                                                                                                 'MIN',
                                                                                                                                 'MAX',
                                                                                                                                 'AVG'],
                                                                                                                     'default': 'ANY',
                                                                                                                     'type': 'str'},
                                                                                                        'measurables': {'type': 'str'},
                                                                                                        'name': {'required': True,
                                                                                                                 'type': 'str'},
                                                                                                        'op': {'choices': ['EQ',
                                                                                                                           'NE',
                                                                                                                           'LT',
                                                                                                                           'GT'],
                                                                                                               'default': 'EQ',
                                                                                                               'type': 'str'},
                                                                                                        'parameters': {'type': 'str'},
                                                                                                        'useRaw': {'default': False,
                                                                                                                   'type': 'bool'},
                                                                                                        'value': {'default': 'FAIL',
                                                                                                                  'type': 'str'}},
                                                                                            'type': 'list'},
                                                                            'name': {'required': True,
                                                                                     'type': 'str'},
                                                                            'op': {'choices': ['OR',
                                                                                               'AND'],
                                                                                   'default': 'OR',
                                                                                   'type': 'str'}},
                                                                'type': 'dict'},
                     'leaveActions': {'type': 'list'},
                     'markEntityAsFailed': {'default': True, 'type': 'bool'},
                     'markEntityAsUnknown': {'default': False, 'type': 'bool'},
                     'name': {'required': True, 'type': 'str'},
                     'severity': {'default': 10, 'type': 'int'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'stateFlappingActions': {'type': 'list'},
                     'stateFlappingCount': {'default': 5, 'type': 'int'},
                     'stateFlappingPeriod': {'default': 300.0, 'type': 'float'}}