#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class MonitoringDataProducerDPU_ArgSpec:
    argument_spec = {'access': {'choices': ['PUBLIC', 'PRIVATE', 'INDIVIDUAL'],
                                'default': 'PUBLIC',
                                'type': 'str'},
                     'associatedUser': {'type': 'str'},
                     'automaticReinitialize': {'default': True, 'type': 'bool'},
                     'cloneFrom': {'default': '', 'type': 'str'},
                     'consolidator': {'type': 'str'},
                     'description': {'type': 'str'},
                     'disableOnHighLoad': {'default': False, 'type': 'bool'},
                     'disableTriggers': {'default': False, 'type': 'bool'},
                     'disabled': {'default': False, 'type': 'bool'},
                     'dpuSettings': {'options': {'configured_events_MonitoringDataProducerDPUSettingsEventGic': {'elements': 'dict',
                                                                                                                 'options': {'counter': {'default': 0,
                                                                                                                                         'type': 'int'},
                                                                                                                             'event': {'choices': ['AW_REQ',
                                                                                                                                                   'AW_BEATS',
                                                                                                                                                   'AW_TRANS',
                                                                                                                                                   'AW_RESP',
                                                                                                                                                   'AW_STL',
                                                                                                                                                   'AW_LAT',
                                                                                                                                                   'AW_REQ_TBU',
                                                                                                                                                   'AR_REQ',
                                                                                                                                                   'AR_BEATS',
                                                                                                                                                   'AR_TRANS',
                                                                                                                                                   'AR_STL',
                                                                                                                                                   'AR_LAT',
                                                                                                                                                   'AR_REQ_TBU',
                                                                                                                                                   'TBU_MISS',
                                                                                                                                                   'TX_DAT_AF',
                                                                                                                                                   'RX_DAT_AF',
                                                                                                                                                   'RETRYQ_CRED',
                                                                                                                                                   'DISABLED'],
                                                                                                                                       'default': 'DISABLED',
                                                                                                                                       'type': 'str'},
                                                                                                                             'index': {'default': 0,
                                                                                                                                       'type': 'int'}},
                                                                                                                 'type': 'list'},
                                                 'configured_events_MonitoringDataProducerDPUSettingsEventL3CacheHalf': {'elements': 'dict',
                                                                                                                         'options': {'counter': {'default': 0,
                                                                                                                                                 'type': 'int'},
                                                                                                                                     'event': {'choices': ['DISABLED',
                                                                                                                                                           'CYCLES',
                                                                                                                                                           'TOTAL_RD_REQ_IN',
                                                                                                                                                           'TOTAL_WR_REQ_IN',
                                                                                                                                                           'TOTAL_WR_DBID_ACK',
                                                                                                                                                           'TOTAL_WR_DATA_IN',
                                                                                                                                                           'TOTAL_WR_COMP',
                                                                                                                                                           'TOTAL_RD_DATA_OUT',
                                                                                                                                                           'TOTAL_CDN_REQ_IN_BANK0',
                                                                                                                                                           'TOTAL_CDN_REQ_IN_BANK1',
                                                                                                                                                           'TOTAL_DDN_REQ_IN_BANK0',
                                                                                                                                                           'TOTAL_DDN_REQ_IN_BANK1',
                                                                                                                                                           'TOTAL_EMEM_RD_RES_IN_BANK0',
                                                                                                                                                           'TOTAL_EMEM_RD_RES_IN_BANK1',
                                                                                                                                                           'TOTAL_CACHE_RD_RES_IN_BANK0',
                                                                                                                                                           'TOTAL_CACHE_RD_RES_IN_BANK1',
                                                                                                                                                           'TOTAL_EMEM_RD_REQ_BANK0',
                                                                                                                                                           'TOTAL_EMEM_RD_REQ_BANK1',
                                                                                                                                                           'TOTAL_EMEM_WR_REQ_BANK0',
                                                                                                                                                           'TOTAL_EMEM_WR_REQ_BANK1',
                                                                                                                                                           'TOTAL_RD_REQ_OUT',
                                                                                                                                                           'TOTAL_WR_REQ_OUT',
                                                                                                                                                           'TOTAL_RD_RES_IN',
                                                                                                                                                           'HITS_BANK0',
                                                                                                                                                           'HITS_BANK1',
                                                                                                                                                           'MISSES_BANK0',
                                                                                                                                                           'MISSES_BANK1',
                                                                                                                                                           'ALLOCATIONS_BANK0',
                                                                                                                                                           'ALLOCATIONS_BANK1',
                                                                                                                                                           'EVICTIONS_BANK0',
                                                                                                                                                           'EVICTIONS_BANK1',
                                                                                                                                                           'DBID_REJECT',
                                                                                                                                                           'WRDB_REJECT_BANK0',
                                                                                                                                                           'WRDB_REJECT_BANK1',
                                                                                                                                                           'CMDQ_REJECT_BANK0',
                                                                                                                                                           'CMDQ_REJECT_BANK1',
                                                                                                                                                           'COB_REJECT_BANK0',
                                                                                                                                                           'COB_REJECT_BANK1',
                                                                                                                                                           'TRB_REJECT_BANK0',
                                                                                                                                                           'TRB_REJECT_BANK1',
                                                                                                                                                           'TAG_REJECT_BANK0',
                                                                                                                                                           'TAG_REJECT_BANK1',
                                                                                                                                                           'ANY_REJECT_BANK0',
                                                                                                                                                           'ANY_REJECT_BANK1'],
                                                                                                                                               'default': 'DISABLED',
                                                                                                                                               'type': 'str'},
                                                                                                                                     'index': {'default': 0,
                                                                                                                                               'type': 'int'}},
                                                                                                                         'type': 'list'},
                                                 'configured_events_MonitoringDataProducerDPUSettingsEventSmmu': {'elements': 'dict',
                                                                                                                  'options': {'counter': {'default': 0,
                                                                                                                                          'type': 'int'},
                                                                                                                              'event': {'choices': ['AW_REQ',
                                                                                                                                                    'AW_BEATS',
                                                                                                                                                    'AW_TRANS',
                                                                                                                                                    'AW_RESP',
                                                                                                                                                    'AW_STL',
                                                                                                                                                    'AW_LAT',
                                                                                                                                                    'AW_REQ_TBU',
                                                                                                                                                    'AR_REQ',
                                                                                                                                                    'AR_BEATS',
                                                                                                                                                    'AR_TRANS',
                                                                                                                                                    'AR_STL',
                                                                                                                                                    'AR_LAT',
                                                                                                                                                    'AR_REQ_TBU',
                                                                                                                                                    'TBU_MISS',
                                                                                                                                                    'TX_DAT_AF',
                                                                                                                                                    'RX_DAT_AF',
                                                                                                                                                    'RETRYQ_CRED',
                                                                                                                                                    'DISABLED'],
                                                                                                                                        'default': 'DISABLED',
                                                                                                                                        'type': 'str'},
                                                                                                                              'index': {'default': 0,
                                                                                                                                        'type': 'int'}},
                                                                                                                  'type': 'list'},
                                                 'configured_events_MonitoringDataProducerDPUSettingsEventTile': {'elements': 'dict',
                                                                                                                  'options': {'counter': {'default': 0,
                                                                                                                                          'type': 'int'},
                                                                                                                              'event': {'choices': ['HNF_REQUESTS',
                                                                                                                                                    'HNF_REJECTS',
                                                                                                                                                    'ALL_BUSY',
                                                                                                                                                    'MAF_BUSY',
                                                                                                                                                    'MAF_REQUESTS',
                                                                                                                                                    'RNF_REQUESTS',
                                                                                                                                                    'REQUEST_TYPE',
                                                                                                                                                    'MEMORY_READS',
                                                                                                                                                    'MEMORY_WRITES',
                                                                                                                                                    'VICTIM_WRITE',
                                                                                                                                                    'POC_FULL',
                                                                                                                                                    'POC_FAIL',
                                                                                                                                                    'POC_SUCCESS',
                                                                                                                                                    'POC_WRITES',
                                                                                                                                                    'POC_READS',
                                                                                                                                                    'FORWARD',
                                                                                                                                                    'RXREQ_HNF',
                                                                                                                                                    'RXRSP_HNF',
                                                                                                                                                    'RXDAT_HNF',
                                                                                                                                                    'TXREQ_HNF',
                                                                                                                                                    'TXRSP_HNF',
                                                                                                                                                    'TXDAT_HNF',
                                                                                                                                                    'TXSNP_HNF',
                                                                                                                                                    'INDEX_MATCH',
                                                                                                                                                    'A72_ACCESS',
                                                                                                                                                    'IO_ACCESS',
                                                                                                                                                    'TSO_WRITE',
                                                                                                                                                    'TSO_CONFLICT',
                                                                                                                                                    'DIR_HIT',
                                                                                                                                                    'HNF_ACCEPTS',
                                                                                                                                                    'REQ_BUF_EMPTY',
                                                                                                                                                    'REQ_BUF_IDLE_MAF',
                                                                                                                                                    'TSO_NOARB',
                                                                                                                                                    'TSO_NOARB_CYCLES',
                                                                                                                                                    'MSS_NO_CREDIT',
                                                                                                                                                    'TXDAT_NO_LCRD',
                                                                                                                                                    'TXSNP_NO_LCRD',
                                                                                                                                                    'TXRSP_NO_LCRD',
                                                                                                                                                    'TXREQ_NO_LCRD',
                                                                                                                                                    'TSO_CL_MATCH',
                                                                                                                                                    'MEMORY_READS_BYPASS',
                                                                                                                                                    'TSO_NOARB_TIMEOUT',
                                                                                                                                                    'ALLOCATE',
                                                                                                                                                    'VICTIM',
                                                                                                                                                    'A72_WRITE',
                                                                                                                                                    'A72_READ',
                                                                                                                                                    'IO_WRITE',
                                                                                                                                                    'IO_READ',
                                                                                                                                                    'TSO_REJECT',
                                                                                                                                                    'TXREQ_RN',
                                                                                                                                                    'TXRSP_RN',
                                                                                                                                                    'TXDAT_RN',
                                                                                                                                                    'RXSNP_RN',
                                                                                                                                                    'RXRSP_RN',
                                                                                                                                                    'RXDAT_RN',
                                                                                                                                                    'DISABLED'],
                                                                                                                                        'default': 'DISABLED',
                                                                                                                                        'type': 'str'},
                                                                                                                              'index': {'default': 0,
                                                                                                                                        'type': 'int'}},
                                                                                                                  'type': 'list'},
                                                 'configured_events_MonitoringDataProducerDPUSettingsEventTilenet': {'elements': 'dict',
                                                                                                                     'options': {'counter': {'default': 0,
                                                                                                                                             'type': 'int'},
                                                                                                                                 'event': {'choices': ['CDN_REQ',
                                                                                                                                                       'DDN_REQ',
                                                                                                                                                       'NDN_REQ',
                                                                                                                                                       'CDN_DIAG_N_OUT_OF_CRED',
                                                                                                                                                       'CDN_DIAG_S_OUT_OF_CRED',
                                                                                                                                                       'CDN_DIAG_E_OUT_OF_CRED',
                                                                                                                                                       'CDN_DIAG_W_OUT_OF_CRED',
                                                                                                                                                       'CDN_DIAG_C_OUT_OF_CRED',
                                                                                                                                                       'CDN_DIAG_N_EGRESS',
                                                                                                                                                       'CDN_DIAG_S_EGRESS',
                                                                                                                                                       'CDN_DIAG_E_EGRESS',
                                                                                                                                                       'CDN_DIAG_W_EGRESS',
                                                                                                                                                       'CDN_DIAG_C_EGRESS',
                                                                                                                                                       'CDN_DIAG_N_INGRESS',
                                                                                                                                                       'CDN_DIAG_S_INGRESS',
                                                                                                                                                       'CDN_DIAG_E_INGRESS',
                                                                                                                                                       'CDN_DIAG_W_INGRESS',
                                                                                                                                                       'CDN_DIAG_C_INGRESS',
                                                                                                                                                       'CDN_DIAG_CORE_SENT',
                                                                                                                                                       'DDN_DIAG_N_OUT_OF_CRED',
                                                                                                                                                       'DDN_DIAG_S_OUT_OF_CRED',
                                                                                                                                                       'DDN_DIAG_E_OUT_OF_CRED',
                                                                                                                                                       'DDN_DIAG_W_OUT_OF_CRED',
                                                                                                                                                       'DDN_DIAG_C_OUT_OF_CRED',
                                                                                                                                                       'DDN_DIAG_N_EGRESS',
                                                                                                                                                       'DDN_DIAG_S_EGRESS',
                                                                                                                                                       'DDN_DIAG_E_EGRESS',
                                                                                                                                                       'DDN_DIAG_W_EGRESS',
                                                                                                                                                       'DDN_DIAG_C_EGRESS',
                                                                                                                                                       'DDN_DIAG_N_INGRESS',
                                                                                                                                                       'DDN_DIAG_S_INGRESS',
                                                                                                                                                       'DDN_DIAG_E_INGRESS',
                                                                                                                                                       'DDN_DIAG_W_INGRESS',
                                                                                                                                                       'DDN_DIAG_C_INGRESS',
                                                                                                                                                       'DDN_DIAG_CORE_SENT',
                                                                                                                                                       'NDN_DIAG_N_OUT_OF_CRED',
                                                                                                                                                       'NDN_DIAG_S_OUT_OF_CRED',
                                                                                                                                                       'NDN_DIAG_E_OUT_OF_CRED',
                                                                                                                                                       'NDN_DIAG_W_OUT_OF_CRED',
                                                                                                                                                       'NDN_DIAG_C_OUT_OF_CRED',
                                                                                                                                                       'NDN_DIAG_N_EGRESS',
                                                                                                                                                       'NDN_DIAG_S_EGRESS',
                                                                                                                                                       'NDN_DIAG_E_EGRESS',
                                                                                                                                                       'NDN_DIAG_W_EGRESS',
                                                                                                                                                       'NDN_DIAG_C_EGRESS',
                                                                                                                                                       'NDN_DIAG_N_INGRESS',
                                                                                                                                                       'NDN_DIAG_S_INGRESS',
                                                                                                                                                       'NDN_DIAG_E_INGRESS',
                                                                                                                                                       'NDN_DIAG_W_INGRESS',
                                                                                                                                                       'NDN_DIAG_C_INGRESS',
                                                                                                                                                       'NDN_DIAG_CORE_SENT',
                                                                                                                                                       'DISABLED'],
                                                                                                                                           'default': 'DISABLED',
                                                                                                                                           'type': 'str'},
                                                                                                                                 'index': {'default': 0,
                                                                                                                                           'type': 'int'}},
                                                                                                                     'type': 'list'},
                                                 'configured_events_MonitoringDataProducerDPUSettingsEventTrio': {'elements': 'dict',
                                                                                                                  'options': {'counter': {'default': 0,
                                                                                                                                          'type': 'int'},
                                                                                                                              'event': {'choices': ['TPIO_DATA_BEAT',
                                                                                                                                                    'TDMA_DATA_BEAT',
                                                                                                                                                    'MAP_DATA_BEAT',
                                                                                                                                                    'TXMSG_DATA_BEAT',
                                                                                                                                                    'TPIO_DATA_PACKET',
                                                                                                                                                    'TDMA_DATA_PACKET',
                                                                                                                                                    'MAP_DATA_PACKET',
                                                                                                                                                    'TXMSG_DATA_PACKET',
                                                                                                                                                    'TDMA_RT_AF',
                                                                                                                                                    'TDMA_PBUF_MAC_AF',
                                                                                                                                                    'TRIO_MAP_WRQ_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_CPL_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_RDQ0_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_RDQ1_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_RDQ2_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_RDQ3_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_RDQ4_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_RDQ5_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_RDQ6_BUF_EMPTY',
                                                                                                                                                    'TRIO_MAP_RDQ7_BUF_EMPTY',
                                                                                                                                                    'TRIO_RING_TX_FLIT_CH0',
                                                                                                                                                    'TRIO_RING_TX_FLIT_CH1',
                                                                                                                                                    'TRIO_RING_TX_FLIT_CH2',
                                                                                                                                                    'TRIO_RING_TX_FLIT_CH3',
                                                                                                                                                    'TRIO_RING_TX_FLIT_CH4',
                                                                                                                                                    'TRIO_RING_RX_FLIT_CH0',
                                                                                                                                                    'TRIO_RING_RX_FLIT_CH1',
                                                                                                                                                    'TRIO_RING_RX_FLIT_CH2',
                                                                                                                                                    'TRIO_RING_RX_FLIT_CH3',
                                                                                                                                                    'DISABLED'],
                                                                                                                                        'default': 'DISABLED',
                                                                                                                                        'type': 'str'},
                                                                                                                              'index': {'default': 0,
                                                                                                                                        'type': 'int'}},
                                                                                                                  'type': 'list'},
                                                 'configured_events_MonitoringDataProducerDPUSettingsEventTriogen': {'elements': 'dict',
                                                                                                                     'options': {'counter': {'default': 0,
                                                                                                                                             'type': 'int'},
                                                                                                                                 'event': {'choices': ['AW_REQ',
                                                                                                                                                       'AW_BEATS',
                                                                                                                                                       'AW_TRANS',
                                                                                                                                                       'AW_RESP',
                                                                                                                                                       'AW_STL',
                                                                                                                                                       'AW_LAT',
                                                                                                                                                       'AW_REQ_TBU',
                                                                                                                                                       'AR_REQ',
                                                                                                                                                       'AR_BEATS',
                                                                                                                                                       'AR_TRANS',
                                                                                                                                                       'AR_STL',
                                                                                                                                                       'AR_LAT',
                                                                                                                                                       'AR_REQ_TBU',
                                                                                                                                                       'TBU_MISS',
                                                                                                                                                       'TX_DAT_AF',
                                                                                                                                                       'RX_DAT_AF',
                                                                                                                                                       'RETRYQ_CRED',
                                                                                                                                                       'DISABLED'],
                                                                                                                                           'default': 'DISABLED',
                                                                                                                                           'type': 'str'},
                                                                                                                                 'index': {'default': 0,
                                                                                                                                           'type': 'int'}},
                                                                                                                     'type': 'list'},
                                                 'enable_ecc': {'default': True, 'type': 'bool'},
                                                 'enable_pcie0': {'default': False, 'type': 'bool'},
                                                 'enable_pcie1': {'default': False,
                                                                  'type': 'bool'}},
                                     'type': 'dict'},
                     'executionMultiplexers_MonitoringCategoryListExecutionMultiplexer': {'elements': 'dict',
                                                                                          'options': {'categories': {'type': 'list'},
                                                                                                      'filterOperation': {'choices': ['NONE',
                                                                                                                                      'INCLUDE',
                                                                                                                                      'EXCLUDE'],
                                                                                                                          'default': 'INCLUDE',
                                                                                                                          'type': 'str'},
                                                                                                      'name': {'required': True,
                                                                                                               'type': 'str'}},
                                                                                          'type': 'list'},
                     'executionMultiplexers_MonitoringDynamicExecutionMultiplexer': {'elements': 'dict',
                                                                                     'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                                 'INCLUDE',
                                                                                                                                 'EXCLUDE'],
                                                                                                                     'default': 'INCLUDE',
                                                                                                                     'type': 'str'},
                                                                                                 'host': {'default': False,
                                                                                                          'type': 'bool'},
                                                                                                 'local': {'default': False,
                                                                                                           'type': 'bool'},
                                                                                                 'name': {'required': True,
                                                                                                          'type': 'str'},
                                                                                                 'offload': {'default': False,
                                                                                                             'type': 'bool'}},
                                                                                     'type': 'list'},
                     'executionMultiplexers_MonitoringLuaExecutionMultiplexer': {'elements': 'dict',
                                                                                 'options': {'code': {'type': 'str'},
                                                                                             'filterOperation': {'choices': ['NONE',
                                                                                                                             'INCLUDE',
                                                                                                                             'EXCLUDE'],
                                                                                                                 'default': 'INCLUDE',
                                                                                                                 'type': 'str'},
                                                                                             'name': {'required': True,
                                                                                                      'type': 'str'},
                                                                                             'notes': {'type': 'str'}},
                                                                                 'type': 'list'},
                     'executionMultiplexers_MonitoringNodeListExecutionMultiplexer': {'elements': 'dict',
                                                                                      'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                                  'INCLUDE',
                                                                                                                                  'EXCLUDE'],
                                                                                                                      'default': 'INCLUDE',
                                                                                                                      'type': 'str'},
                                                                                                  'name': {'required': True,
                                                                                                           'type': 'str'},
                                                                                                  'nodes': {'type': 'list'}},
                                                                                      'type': 'list'},
                     'executionMultiplexers_MonitoringOverlayListExecutionMultiplexer': {'elements': 'dict',
                                                                                         'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                                     'INCLUDE',
                                                                                                                                     'EXCLUDE'],
                                                                                                                         'default': 'INCLUDE',
                                                                                                                         'type': 'str'},
                                                                                                     'name': {'required': True,
                                                                                                              'type': 'str'},
                                                                                                     'overlays': {'type': 'list'}},
                                                                                         'type': 'list'},
                     'executionMultiplexers_MonitoringResourceExecutionMultiplexer': {'elements': 'dict',
                                                                                      'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                                  'INCLUDE',
                                                                                                                                  'EXCLUDE'],
                                                                                                                      'default': 'INCLUDE',
                                                                                                                      'type': 'str'},
                                                                                                  'name': {'required': True,
                                                                                                           'type': 'str'},
                                                                                                  'op': {'choices': ['OR',
                                                                                                                     'AND'],
                                                                                                         'default': 'OR',
                                                                                                         'type': 'str'},
                                                                                                  'resources': {'type': 'list'}},
                                                                                      'type': 'list'},
                     'executionMultiplexers_MonitoringTypeExecutionMultiplexer': {'elements': 'dict',
                                                                                  'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                              'INCLUDE',
                                                                                                                              'EXCLUDE'],
                                                                                                                  'default': 'INCLUDE',
                                                                                                                  'type': 'str'},
                                                                                              'name': {'required': True,
                                                                                                       'type': 'str'},
                                                                                              'types': {'type': 'list'}},
                                                                                  'type': 'list'},
                     'extra_values': {'type': 'json'},
                     'fuzzyOffset': {'default': 0.0, 'type': 'float'},
                     'gap': {'default': 0, 'type': 'int'},
                     'interval': {'default': 120.0, 'type': 'float'},
                     'intervals': {'type': 'list'},
                     'introduceNaN': {'default': True, 'type': 'bool'},
                     'maxAge': {'default': 0.0, 'type': 'float'},
                     'maxMeasurables': {'default': 512, 'type': 'int'},
                     'maxSamples': {'default': 4096, 'type': 'int'},
                     'name': {'required': True, 'type': 'str'},
                     'nodeExecutionFilters_MonitoringCategoryListExecutionFilter': {'elements': 'dict',
                                                                                    'options': {'categories': {'type': 'list'},
                                                                                                'filterOperation': {'choices': ['NONE',
                                                                                                                                'INCLUDE',
                                                                                                                                'EXCLUDE'],
                                                                                                                    'default': 'INCLUDE',
                                                                                                                    'type': 'str'},
                                                                                                'name': {'required': True,
                                                                                                         'type': 'str'}},
                                                                                    'type': 'list'},
                     'nodeExecutionFilters_MonitoringLuaExecutionFilter': {'elements': 'dict',
                                                                           'options': {'code': {'type': 'str'},
                                                                                       'filterOperation': {'choices': ['NONE',
                                                                                                                       'INCLUDE',
                                                                                                                       'EXCLUDE'],
                                                                                                           'default': 'INCLUDE',
                                                                                                           'type': 'str'},
                                                                                       'name': {'required': True,
                                                                                                'type': 'str'},
                                                                                       'notes': {'type': 'str'}},
                                                                           'type': 'list'},
                     'nodeExecutionFilters_MonitoringNodeListExecutionFilter': {'elements': 'dict',
                                                                                'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                            'INCLUDE',
                                                                                                                            'EXCLUDE'],
                                                                                                                'default': 'INCLUDE',
                                                                                                                'type': 'str'},
                                                                                            'name': {'required': True,
                                                                                                     'type': 'str'},
                                                                                            'nodes': {'type': 'list'}},
                                                                                'type': 'list'},
                     'nodeExecutionFilters_MonitoringOverlayListExecutionFilter': {'elements': 'dict',
                                                                                   'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                               'INCLUDE',
                                                                                                                               'EXCLUDE'],
                                                                                                                   'default': 'INCLUDE',
                                                                                                                   'type': 'str'},
                                                                                               'name': {'required': True,
                                                                                                        'type': 'str'},
                                                                                               'overlays': {'type': 'list'}},
                                                                                   'type': 'list'},
                     'nodeExecutionFilters_MonitoringResourceExecutionFilter': {'elements': 'dict',
                                                                                'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                            'INCLUDE',
                                                                                                                            'EXCLUDE'],
                                                                                                                'default': 'INCLUDE',
                                                                                                                'type': 'str'},
                                                                                            'name': {'required': True,
                                                                                                     'type': 'str'},
                                                                                            'op': {'choices': ['OR',
                                                                                                               'AND'],
                                                                                                   'default': 'OR',
                                                                                                   'type': 'str'},
                                                                                            'resources': {'type': 'list'}},
                                                                                'type': 'list'},
                     'nodeExecutionFilters_MonitoringTypeExecutionFilter': {'elements': 'dict',
                                                                            'options': {'cloudNode': {'default': False,
                                                                                                      'type': 'bool'},
                                                                                        'dpuNode': {'default': False,
                                                                                                    'type': 'bool'},
                                                                                        'filterOperation': {'choices': ['NONE',
                                                                                                                        'INCLUDE',
                                                                                                                        'EXCLUDE'],
                                                                                                            'default': 'INCLUDE',
                                                                                                            'type': 'str'},
                                                                                        'headNode': {'default': False,
                                                                                                     'type': 'bool'},
                                                                                        'liteNode': {'default': False,
                                                                                                     'type': 'bool'},
                                                                                        'name': {'required': True,
                                                                                                 'type': 'str'},
                                                                                        'physicalNode': {'default': False,
                                                                                                         'type': 'bool'}},
                                                                            'type': 'list'},
                     'notes': {'type': 'str'},
                     'offset': {'default': 0.0, 'type': 'float'},
                     'postJob': {'default': False, 'type': 'bool'},
                     'preJob': {'default': False, 'type': 'bool'},
                     'startupDelay': {'default': 0.0, 'type': 'float'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'suppressedByGoingDown': {'default': False, 'type': 'bool'},
                     'when': {'choices': ['TIMED', 'ONDEMAND', 'OOB', 'ONSTART'],
                              'default': 'TIMED',
                              'type': 'str'}}