---
- name: Unbind SSH port {{ software_image.tunnel }} from chroot /cm/images/{{ software_image.name }}
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} BRIGHTCOMPUTING.BCM.SOFTWARE_IMAGE_TUNNEL:{{ software_image.name }}.chroot ANSIBLE MANAGED BLOCK"
    marker_end: 'END  '
    state: absent
  notify:
    - Restart ssh

- name: Close SSH port {{ software_image.tunnel }}
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} BRIGHTCOMPUTING.BCM.SOFTWARE_IMAGE_TUNNEL:{{ software_image.name }}.listen ANSIBLE MANAGED BLOCK"
    marker_end: 'END  '
    state: absent
  notify:
    - Restart ssh

# not supported on c8u4,s12sp5,s15sp2,rhel8u4
# - name: Unbind SSH port {{ software_image.tunnel }} from chroot {{ software_image_root_dir }}/{{ software_image.name }}
#   file:
#     path: /etc/ssh/sshd_config.d/brightcomputing.bcm.software_image_tunnel.{{ software_image.name  }}
#     state: absent
#   notify:
#     - Restart ssh

- name: Unount pseudo filesystems under {{ software_image_root_dir }}/{{ software_image.name }}
  ansible.posix.mount:
    path: "{{ software_image_root_dir }}/{{ software_image.name }}{{ mount }}"
    src: "{{ mount }}"
    opts: bind
    state: unmounted
    fstype: none
  loop:
    - /dev
    - /proc
    - /sys
  loop_control:
    loop_var: mount

- name: Remove host's resolv.conf from chroot
  file:
    path: "{{ software_image_root_dir }}/{{ software_image.name }}/run/systemd/resolve/resolv.conf"
    state: absent

- name: Remove /etc/fstab.{{ software_image.name }} (temporary chroot fstab)
  file:
    path: /etc/fstab.{{ software_image.name }}
    state: absent
