---
- name: Open SSH tunnels
  include_tasks:
    file: open-tunnel.yml
  vars:
    software_image:
      name: "{{ software_image_name }}"
      tunnel: "{{ hostvars[software_image_name].ansible_port }}"
  loop: "{{ groups[software_image_group_name] }}"
  loop_control:
    label: "{{ software_image_name }}"
    loop_var: software_image_name

- meta: flush_handlers
