#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

from __future__ import annotations


class RPCTimeouts:
    timeouts = {
        ('cmcert', 'recreateComponentCertificate'): 60,
        ('cmcert', 'precreateComponentCertificate'): 900,
        ('cmcert', 'invalidateComponent'): 60,
        ('cmcert', 'pinvalidateComponent'): 900,
        ('cmcloud', 'terminate'): 300,
        ('cmcloud', 'listAzureBlobs'): 600,
        ('cmcloud', 'listAmazonImages'): 600,
        ('cmdevice', 'queryRemoveDevices'): 3600,
        ('cmdevice', 'removeDevices'): 3600,
        ('cmdevice', 'queryRemoveCategories'): 3600,
        ('cmdevice', 'removeCategories'): 3600,
        ('cmdevice', 'getPortByMac'): 1200,
        ('cmdevice', 'addDevices'): 3600,
        ('cmdevice', 'updateDevices'): 3600,
        ('cmdevice', 'validateDevices'): 3600,
        ('cmdevice', 'addCategories'): 3600,
        ('cmdevice', 'updateCategories'): 3600,
        ('cmdevice', 'addNodeGroups'): 3600,
        ('cmdevice', 'updateNodeGroups'): 3600,
        ('cmdevice', 'validateNodeGroups'): 3600,
        ('cmdevice', 'queryRemoveNodeGroups'): 3600,
        ('cmdevice', 'getAdditionalNodeInfo'): 300,
        ('cmdevice', 'pgetAdditionalNodeInfo'): 900,
        ('cmdevice', 'getAdditionalNodeInfoForNodes'): 900,
        ('cmdevice', 'forceReconnect'): 10,
        ('cmdevice', 'pforceReconnect'): 10,
        ('cmdevice', 'parallelPingAllToAll'): 360,
        ('cmdevice', 'pingAllToAll'): 360,
        ('cmdevice', 'ppingAllToAll'): 360,
        ('cmdevice', 'statisticsPingAllToAll'): 360,
        ('cmdevice', 'deviceHardwareInventoryInfo'): 1800,
        ('cmdevice', 'getFreePorts'): 15,
        ('cmdevice', 'pgetFreePorts'): 15,
        ('cmdevice', 'bmcIdentify'): 900,
        ('cmdevice', 'bmcIsIdentified'): 900,
        ('cmdevice', 'bmcReset'): 900,
        ('cmdevice', 'bmcEventLogs'): 900,
        ('cmdevice', 'bmcClearEventLogs'): 900,
        ('cmdevice', 'getRedFishPath'): 600,
        ('cmdevice', 'postRedFishPath'): 600,
        ('cmdevice', 'patchRedFishPath'): 600,
        ('cmdevice', 'putRedFishPath'): 600,
        ('cmdevice', 'deleteRedFishPath'): 600,
        ('cmdevice', 'biosFetch'): 900,
        ('cmdevice', 'biosCheck'): 900,
        ('cmdevice', 'biosApply'): 900,
        ('cmdevice', 'biosModels'): 60,
        ('cmdevice', 'biosTemplates'): 60,
        ('cmdevice', 'biosProfiles'): 60,
        ('cmdevice', 'firmwareUpload'): 900,
        ('cmdevice', 'firmwareRemove'): 900,
        ('cmdevice', 'firmwareFlash'): 900,
        ('cmdevice', 'ibswitchShow'): 60,
        ('cmdevice', 'ibswitchImages'): 60,
        ('cmdevice', 'ibswitchInterfaces'): 60,
        ('cmdevice', 'ibswitchList'): 60,
        ('cmdevice', 'ibswitchUpgrade'): 3600,
        ('cmdevice', 'dpuShow'): 60,
        ('cmdevice', 'dpuApply'): 600,
        ('cmdevice', 'dpuReset'): 360,
        ('cmdevice', 'dpuListBfb'): 60,
        ('cmdevice', 'dpuPushBfb'): 1800,
        ('cmdevice', 'migEnable'): 60,
        ('cmdevice', 'migDisable'): 60,
        ('cmdevice', 'migStatus'): 60,
        ('cmdevice', 'migApply'): 120,
        ('cmdevice', 'migProfiles'): 60,
        ('cmdevice', 'migClear'): 120,
        ('cmdevice', 'migShow'): 60,
        ('cmdevice', 'migEnablePairs'): 60,
        ('cmdevice', 'migDisablePairs'): 60,
        ('cmdevice', 'migStatusPairs'): 60,
        ('cmdevice', 'migApplyPairs'): 120,
        ('cmdevice', 'migProfilesPairs'): 60,
        ('cmdevice', 'migClearPairs'): 120,
        ('cmdevice', 'migShowPairs'): 60,
        ('cmdevice', 'gpuReset'): 360,
        ('cmdevice', 'pgpuReset'): 360,
        ('cmdevice', 'backupDeviceCommands'): 120,
        ('cmdevice', 'listDeviceCommands'): 120,
        ('cmdevice', 'plistDeviceCommands'): 120,
        ('cmdevice', 'showDeviceCommands'): 120,
        ('cmdevice', 'pshowDeviceCommands'): 120,
        ('cmdevice', 'showDeviceCommandsYAML'): 120,
        ('cmdevice', 'pshowDeviceCommandsYAML'): 120,
        ('cmdevice', 'diffDeviceCommands'): 120,
        ('cmdevice', 'pdiffDeviceCommands'): 120,
        ('cmdevice', 'applyDeviceCommands'): 120,
        ('cmdevice', 'papplyDeviceCommands'): 120,
        ('cmdevice', 'saveDeviceCommands'): 120,
        ('cmdevice', 'psaveDeviceCommands'): 120,
        ('cmdevice', 'detachDeviceCommands'): 120,
        ('cmdevice', 'pdetachDeviceCommands'): 120,
        ('cmdevice', 'getDhcpdLeases'): 120,
        ('cmdevice', 'pgetDhcpdLeases'): 120,
        ('cmdevice', 'nvfabricStart'): 300,
        ('cmdevice', 'pnvfabricStart'): 300,
        ('cmdevice', 'nvfabricStop'): 300,
        ('cmdevice', 'pnvfabricStop'): 300,
        ('cmdevice', 'liteDaemonDownloadPackages'): 600,
        ('cmdevice', 'liteDaemonPackagesStatus'): 600,
        ('cmdevice', 'liteDaemonInstall'): 600,
        ('cmdevice', 'liteDaemonRemove'): 600,
        ('cmkube', 'getCapiImageVersions'): 120,
        ('cmkube', 'addCapiImageVersions'): 120,
        ('cmkube', 'removeCapiImageVersions'): 120,
        ('cmkube', 'clearCapiImageVersions'): 120,
        ('cmkube', 'updateCapiImageVersions'): 120,
        ('cmmain', 'verifyAPI'): 10,
        ('cmmain', 'verifyAPINoEvents'): 10,
        ('cmmain', 'heartBeat'): 5,
        ('cmmain', 'getHeadNodeIPsForIP'): 12,
        ('cmmain', 'activeHeadNodeHasBeenManuallyPoweredOff'): 600,
        ('cmmon', 'plot'): 600,
        ('cmmon', 'sample'): 600,
        ('cmmon', 'performHealthCheckForWlmJobOnNodes'): 600,
        ('cmmon', 'performHealthCheckForWlmJob'): 600,
        ('cmmon', 'executePrometheusQueryByUuid'): 600,
        ('cmmon', 'executePrometheusQueryByUuids'): 600,
        ('cmmon', 'executePrometheusQuery'): 600,
        ('cmmon', 'executePrometheusQueries'): 600,
        ('cmnet', 'addNetworks'): 3600,
        ('cmnet', 'updateNetworks'): 3600,
        ('cmnet', 'validateNetworks'): 3600,
        ('cmnet', 'queryRemoveNetworks'): 3600,
        ('cmnet', 'removeNetworks'): 3600,
        ('cmpart', 'updateEdgeSites'): 3600,
        ('cmpart', 'addEdgeSites'): 3600,
        ('cmpart', 'removeEdgeSites'): 3600,
        ('cmpart', 'validateEdgeSites'): 3600,
        ('cmpart', 'queryRemoveEdgeSites'): 3600,
        ('cmpart', 'failoverStatus'): 5,
        ('cmpart', 'cmdaemonBecameActiveHeadNode'): 600,
        ('cmpart', 'failoverMakeActiveHeadNode'): 600,
        ('cmpart', 'getMysqlMasterStatus'): 15,
        ('cmpart', 'startQuorum'): 10,
        ('cmpart', 'decideQuorum'): 10,
        ('cmprov', 'getFSPartInfo'): 1800,
        ('cmprov', 'pgetFSPartInfo'): 1800,
        ('cmserv', 'startOSService'): 360,
        ('cmserv', 'pstartOSService'): 360,
        ('cmserv', 'stopOSService'): 360,
        ('cmserv', 'pstopOSService'): 360,
        ('cmserv', 'restartOSService'): 360,
        ('cmserv', 'prestartOSService'): 360,
        ('cmserv', 'reloadOSService'): 360,
        ('cmserv', 'preloadOSService'): 360,
        ('cmserv', 'resetOSService'): 360,
        ('cmserv', 'presetOSService'): 360,
        ('cmserv', 'callInitScript'): 360,
        ('cmserv', 'pcallInitScript'): 360,
        ('cmsession', 'endNodeSession'): 15,
        ('cmsession', 'endSession'): 15,
        ('cmsession', 'waitForEvent'): 86400,
        ('cmsession', 'waitForEvents'): 86400,
        ('cmsession', 'handleEvent'): 10,
        ('cmsession', 'handleEvents'): 30,
        ('cmstatus', 'setUpDownClosedMuted'): 10,
        ('cmstatus', 'psetUpDownClosedMuted'): 60,
    }

    @classmethod
    def get(cls, service: str, call: str) -> float:
        return cls.timeouts.get((service, call), 60.0)
