from enum import Enum
from enum import auto

from pythoncm.entity.meta_data import MetaData
from pythoncm.entity.meta_data_field import MetaDataField
from pythoncm.entity.metadata.entity import Entity


class SysInfoCollector(Entity):
    class CGroup(Enum):
        UNDEFINED = auto()
        V1 = auto()
        V2 = auto()

    def __init__(self):
        super().__init__()
        self.meta.add(
            MetaDataField(
                name="ref_device_uuid",
                kind=MetaData.Type.UUID,
                description="Device",
                default=self.zero_uuid,
            )
        )
        self.meta.add(
            MetaDataField(
                name="cpus",
                kind=MetaData.Type.ENTITY,
                instance='CPUInfo',
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="disks",
                kind=MetaData.Type.ENTITY,
                instance='DiskInfo',
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="gpus",
                kind=MetaData.Type.ENTITY,
                instance='GPUInfo',
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="dpus",
                kind=MetaData.Type.ENTITY,
                instance='DPUInfo',
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="fpgas",
                kind=MetaData.Type.ENTITY,
                instance='FPGAInfo',
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="memory",
                kind=MetaData.Type.ENTITY,
                instance='MemoryInfo',
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="biosVersion",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="biosVendor",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="biosDate",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="motherboardManufacturer",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="motherboardName",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="memoryTotal",
                kind=MetaData.Type.UINT,
                default=0,
            )
        )
        self.meta.add(
            MetaDataField(
                name="memorySwap",
                kind=MetaData.Type.UINT,
                default=0,
            )
        )
        self.meta.add(
            MetaDataField(
                name="diskCount",
                kind=MetaData.Type.UINT,
                default=0,
            )
        )
        self.meta.add(
            MetaDataField(
                name="diskTotalSpace",
                kind=MetaData.Type.UINT,
                default=0,
            )
        )
        self.meta.add(
            MetaDataField(
                name="osName",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="osVersion",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="osFlavor",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="cgroup",
                kind=MetaData.Type.ENUM,
                options=[
                    self.CGroup.UNDEFINED,
                    self.CGroup.V1,
                    self.CGroup.V2,
                ],
                diff_type=MetaDataField.Diff.enum,
                enum_type=self.CGroup,
                default=self.CGroup.UNDEFINED,
            )
        )
        self.meta.add(
            MetaDataField(
                name="vendorTag",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="systemName",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="systemManufacturer",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="nics",
                kind=MetaData.Type.STRING,
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="ibGUIDs",
                kind=MetaData.Type.STRING,
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="bootIf",
                kind=MetaData.Type.STRING,
                default='',
            )
        )
        self.meta.add(
            MetaDataField(
                name="interconnects",
                kind=MetaData.Type.STRING,
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="raidControllers",
                kind=MetaData.Type.STRING,
                vector=True,
                default=[],
            )
        )
        self.meta.add(
            MetaDataField(
                name="extra",
                kind=MetaData.Type.JSON,
                default=None,
            )
        )
        self.meta.add(
            MetaDataField(
                name="virtualCluster",
                kind=MetaData.Type.BOOL,
                default=False,
            )
        )
        self.meta.add(
            MetaDataField(
                name="seLinux",
                kind=MetaData.Type.BOOL,
                default=False,
            )
        )
        self.meta.add(
            MetaDataField(
                name="nvsm",
                kind=MetaData.Type.BOOL,
                default=False,
            )
        )
        self.meta.add(
            MetaDataField(
                name="fips",
                kind=MetaData.Type.BOOL,
                default=False,
            )
        )
        self.meta.add(
            MetaDataField(
                name="clusterRandomNumber",
                kind=MetaData.Type.UINT,
                default=0,
            )
        )
        self.meta.add(
            MetaDataField(
                name="updateCount",
                kind=MetaData.Type.UINT,
                default=0,
            )
        )
        self.meta.add(
            MetaDataField(
                name="timestamp",
                kind=MetaData.Type.TIMESTAMP,
                default=0,
            )
        )
        self.baseType = 'SysInfoCollector'
        self.service_type = self.baseType
        self.allTypes = ['SysInfoCollector']
        self.top_level = False
        self.leaf_entity = True
        self.add_to_cluster = False
        self.allow_commit = False

