#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class LSFJobQueue_ArgSpec:
    argument_spec = {'administrators': {'type': 'str'},
                     'backfill': {'type': 'str'},
                     'categories': {'type': 'list'},
                     'chkPnt': {'type': 'str'},
                     'cloneFrom': {'default': '', 'type': 'str'},
                     'computeNodes': {'type': 'list'},
                     'corelimit': {'default': 0, 'type': 'int'},
                     'cpulimit': {'type': 'str'},
                     'datalimit': {'default': 0, 'type': 'int'},
                     'defaultQueue': {'default': False, 'type': 'bool'},
                     'default_host_spec': {'type': 'str'},
                     'description': {'type': 'str'},
                     'dispatch_window': {'type': 'str'},
                     'epilog': {'type': 'str'},
                     'exclusive': {'type': 'str'},
                     'fairshare': {'type': 'str'},
                     'filelimit': {'default': 0, 'type': 'int'},
                     'hjob_limit': {'default': 0, 'type': 'int'},
                     'hostEpilog': {'default': '/cm/local/apps/cmd/scripts/epilog', 'type': 'str'},
                     'hostProlog': {'default': '/cm/local/apps/cmd/scripts/prolog', 'type': 'str'},
                     'hosts': {'type': 'str'},
                     'ignore_deadline': {'type': 'str'},
                     'interactive': {'type': 'str'},
                     'io': {'type': 'str'},
                     'it': {'type': 'str'},
                     'job_accept_interval': {'default': 0, 'type': 'int'},
                     'job_controls': {'type': 'str'},
                     'job_starter': {'type': 'str'},
                     'load_index': {'type': 'str'},
                     'ls': {'type': 'str'},
                     'mem': {'type': 'str'},
                     'memlimit': {'type': 'str'},
                     'mig': {'default': 0, 'type': 'int'},
                     'name': {'required': True, 'type': 'str'},
                     'new_job_sched_delay': {'default': 0, 'type': 'int'},
                     'nice': {'default': 0, 'type': 'int'},
                     'nodegroups': {'type': 'list'},
                     'options': {'type': 'list'},
                     'overlays': {'type': 'list'},
                     'pg': {'type': 'str'},
                     'pjob_limit': {'default': 0, 'type': 'int'},
                     'pre_post_exec_user': {'default': 'root', 'type': 'str'},
                     'preemption': {'type': 'str'},
                     'priority': {'default': 0, 'type': 'int'},
                     'processlimit': {'type': 'str'},
                     'proclimit': {'type': 'str'},
                     'prolog': {'type': 'str'},
                     'qjob_limit': {'default': 0, 'type': 'int'},
                     'r15m': {'type': 'str'},
                     'r15s': {'type': 'str'},
                     'r1m': {'type': 'str'},
                     'require_exit_values': {'type': 'str'},
                     'rerunnable': {'type': 'str'},
                     'res_req': {'type': 'str'},
                     'resume_cond': {'type': 'str'},
                     'run_window': {'type': 'str'},
                     'runlimit': {'type': 'str'},
                     'slot_reserve': {'default': 0, 'type': 'int'},
                     'stacklimit': {'default': 0, 'type': 'int'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'stop_cond': {'type': 'str'},
                     'swaplimit': {'default': 0, 'type': 'int'},
                     'swp': {'type': 'str'},
                     'terminate_when': {'type': 'str'},
                     'tmp': {'type': 'str'},
                     'ujob_limit': {'default': 0, 'type': 'int'},
                     'users': {'type': 'str'},
                     'ut': {'type': 'str'},
                     'wlmCluster': {'type': 'str'}}