---
# Example inventory for OpenShift cluster deployment
#
# This inventory defines an OpenShift cluster with:
# - 3 master nodes
# - 2 initial worker nodes
# - Examples for expanding with additional workers
#
# Usage:
#   ansible-playbook -i inventory/examples/openshift_cluster/hosts.yml playbooks/deploy_openshift_cluster.yml
#
# Prerequisites:
#   1. Generate OpenShift agent ISO:
#      openshift-install agent create image
#
#   2. Extract or generate Ignition files for each node
#
#   3. Update ignition_file paths below to match your setup

all:
  children:
    bcm_headnode:
      hosts:
        bcm-headnode:
          ansible_host: 192.168.122.163
          ansible_user: root
          ansible_password: redhat
          # Or use SSH key authentication:
          # ansible_ssh_private_key_file: ~/.ssh/id_rsa

      vars:
        # ================================================================
        # Cluster Configuration
        # ================================================================
        cluster_name: prod
        cluster_type: openshift
        openshift_version: "4.16"

        # ================================================================
        # OpenShift ISO Configuration
        # ================================================================
        # Path to OpenShift agent ISO (generated by openshift-install)
        openshift_iso_path: /root/openshift-install/agent.x86_64.iso

        # CoreOS installation device
        install_device: /dev/sda

        # ================================================================
        # Node Roles
        # ================================================================
        node_roles:
          - name: master
            category: "openshift-{{ openshift_version | replace('.', '') }}-{{ cluster_name }}-master"

          - name: worker
            category: "openshift-{{ openshift_version | replace('.', '') }}-{{ cluster_name }}-worker"

          # Uncomment if deploying infrastructure nodes
          # - name: infra
          #   category: "openshift-{{ openshift_version | replace('.', '') }}-{{ cluster_name }}-infra"

        # ================================================================
        # Cluster Nodes
        # ================================================================
        cluster_nodes:
          # ============================================================
          # Master Nodes
          # ============================================================
          - name: master-0
            mac: "52:54:00:AA:BB:01"
            ip: "10.141.160.50"
            role: master
            # Path to Ignition file (generated by openshift-install)
            ignition_file: /root/openshift-install/ignition/master-0.ign
            rack: "B1"
            rackposition: 1

          - name: master-1
            mac: "52:54:00:AA:BB:02"
            ip: "10.141.160.51"
            role: master
            ignition_file: /root/openshift-install/ignition/master-1.ign
            rack: "B1"
            rackposition: 2

          - name: master-2
            mac: "52:54:00:AA:BB:03"
            ip: "10.141.160.52"
            role: master
            ignition_file: /root/openshift-install/ignition/master-2.ign
            rack: "B1"
            rackposition: 3

          # ============================================================
          # Worker Nodes (Initial Deployment)
          # ============================================================
          - name: worker-0
            mac: "52:54:00:CC:DD:01"
            ip: "10.141.160.60"
            role: worker
            ignition_file: /root/openshift-install/ignition/worker-0.ign
            rack: "B2"
            rackposition: 10

          - name: worker-1
            mac: "52:54:00:CC:DD:02"
            ip: "10.141.160.61"
            role: worker
            ignition_file: /root/openshift-install/ignition/worker-1.ign
            rack: "B2"
            rackposition: 11

          # ============================================================
          # Additional Workers (Expansion Example)
          # ============================================================
          # To add these nodes later:
          # 1. Generate Ignition file:
          #    oc extract -n openshift-machine-api secret/worker-user-data \
          #      --keys=userData --to=/root/ignition/worker-2.ign
          # 2. Uncomment the node definition below
          # 3. Re-run the playbook

          # - name: worker-2
          #   mac: "52:54:00:EE:FF:01"
          #   ip: "10.141.160.62"
          #   role: worker
          #   ignition_file: /root/ignition/worker-2.ign
          #   rack: "B2"
          #   rackposition: 12

          # - name: worker-3
          #   mac: "52:54:00:EE:FF:02"
          #   ip: "10.141.160.63"
          #   role: worker
          #   ignition_file: /root/ignition/worker-3.ign
          #   rack: "B2"
          #   rackposition: 13

          # ============================================================
          # Infrastructure Nodes (Optional)
          # ============================================================
          # Uncomment if deploying dedicated infrastructure nodes

          # - name: infra-0
          #   mac: "52:54:00:FF:AA:01"
          #   ip: "10.141.160.70"
          #   role: infra
          #   ignition_file: /root/openshift-install/ignition/infra-0.ign
          #   rack: "B3"
          #   rackposition: 1
