#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class MonitoringDataProducerPRS_ArgSpec:
    argument_spec = {'access': {'choices': ['PUBLIC', 'PRIVATE', 'INDIVIDUAL'],
                                'default': 'PUBLIC',
                                'type': 'str'},
                     'associatedUser': {'type': 'str'},
                     'automaticReinitialize': {'default': True, 'type': 'bool'},
                     'cloneFrom': {'default': '', 'type': 'str'},
                     'consolidator': {'type': 'str'},
                     'description': {'type': 'str'},
                     'disableOnHighLoad': {'default': False, 'type': 'bool'},
                     'disableTriggers': {'default': False, 'type': 'bool'},
                     'disabled': {'default': False, 'type': 'bool'},
                     'executionMultiplexers_MonitoringCategoryListExecutionMultiplexer': {'elements': 'dict',
                                                                                          'options': {'categories': {'type': 'list'},
                                                                                                      'filterOperation': {'choices': ['NONE',
                                                                                                                                      'INCLUDE',
                                                                                                                                      'EXCLUDE'],
                                                                                                                          'default': 'INCLUDE',
                                                                                                                          'type': 'str'},
                                                                                                      'name': {'required': True,
                                                                                                               'type': 'str'}},
                                                                                          'type': 'list'},
                     'executionMultiplexers_MonitoringDynamicExecutionMultiplexer': {'elements': 'dict',
                                                                                     'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                                 'INCLUDE',
                                                                                                                                 'EXCLUDE'],
                                                                                                                     'default': 'INCLUDE',
                                                                                                                     'type': 'str'},
                                                                                                 'host': {'default': False,
                                                                                                          'type': 'bool'},
                                                                                                 'local': {'default': False,
                                                                                                           'type': 'bool'},
                                                                                                 'name': {'required': True,
                                                                                                          'type': 'str'},
                                                                                                 'offload': {'default': False,
                                                                                                             'type': 'bool'}},
                                                                                     'type': 'list'},
                     'executionMultiplexers_MonitoringLuaExecutionMultiplexer': {'elements': 'dict',
                                                                                 'options': {'code': {'type': 'str'},
                                                                                             'filterOperation': {'choices': ['NONE',
                                                                                                                             'INCLUDE',
                                                                                                                             'EXCLUDE'],
                                                                                                                 'default': 'INCLUDE',
                                                                                                                 'type': 'str'},
                                                                                             'name': {'required': True,
                                                                                                      'type': 'str'},
                                                                                             'notes': {'type': 'str'}},
                                                                                 'type': 'list'},
                     'executionMultiplexers_MonitoringNodeListExecutionMultiplexer': {'elements': 'dict',
                                                                                      'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                                  'INCLUDE',
                                                                                                                                  'EXCLUDE'],
                                                                                                                      'default': 'INCLUDE',
                                                                                                                      'type': 'str'},
                                                                                                  'name': {'required': True,
                                                                                                           'type': 'str'},
                                                                                                  'nodes': {'type': 'list'}},
                                                                                      'type': 'list'},
                     'executionMultiplexers_MonitoringOverlayListExecutionMultiplexer': {'elements': 'dict',
                                                                                         'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                                     'INCLUDE',
                                                                                                                                     'EXCLUDE'],
                                                                                                                         'default': 'INCLUDE',
                                                                                                                         'type': 'str'},
                                                                                                     'name': {'required': True,
                                                                                                              'type': 'str'},
                                                                                                     'overlays': {'type': 'list'}},
                                                                                         'type': 'list'},
                     'executionMultiplexers_MonitoringResourceExecutionMultiplexer': {'elements': 'dict',
                                                                                      'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                                  'INCLUDE',
                                                                                                                                  'EXCLUDE'],
                                                                                                                      'default': 'INCLUDE',
                                                                                                                      'type': 'str'},
                                                                                                  'name': {'required': True,
                                                                                                           'type': 'str'},
                                                                                                  'op': {'choices': ['OR',
                                                                                                                     'AND'],
                                                                                                         'default': 'OR',
                                                                                                         'type': 'str'},
                                                                                                  'resources': {'type': 'list'}},
                                                                                      'type': 'list'},
                     'executionMultiplexers_MonitoringTypeExecutionMultiplexer': {'elements': 'dict',
                                                                                  'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                              'INCLUDE',
                                                                                                                              'EXCLUDE'],
                                                                                                                  'default': 'INCLUDE',
                                                                                                                  'type': 'str'},
                                                                                              'name': {'required': True,
                                                                                                       'type': 'str'},
                                                                                              'types': {'type': 'list'}},
                                                                                  'type': 'list'},
                     'extra_values': {'type': 'json'},
                     'fuzzyOffset': {'default': 0.0, 'type': 'float'},
                     'gap': {'default': 0, 'type': 'int'},
                     'interval': {'default': 120.0, 'type': 'float'},
                     'intervals': {'type': 'list'},
                     'introduceNaN': {'default': True, 'type': 'bool'},
                     'maxAge': {'default': 0.0, 'type': 'float'},
                     'maxMeasurables': {'default': 512, 'type': 'int'},
                     'maxSampleAge': {'default': 300.0, 'type': 'float'},
                     'maxSamples': {'default': 4096, 'type': 'int'},
                     'name': {'required': True, 'type': 'str'},
                     'nodeExecutionFilters_MonitoringCategoryListExecutionFilter': {'elements': 'dict',
                                                                                    'options': {'categories': {'type': 'list'},
                                                                                                'filterOperation': {'choices': ['NONE',
                                                                                                                                'INCLUDE',
                                                                                                                                'EXCLUDE'],
                                                                                                                    'default': 'INCLUDE',
                                                                                                                    'type': 'str'},
                                                                                                'name': {'required': True,
                                                                                                         'type': 'str'}},
                                                                                    'type': 'list'},
                     'nodeExecutionFilters_MonitoringLuaExecutionFilter': {'elements': 'dict',
                                                                           'options': {'code': {'type': 'str'},
                                                                                       'filterOperation': {'choices': ['NONE',
                                                                                                                       'INCLUDE',
                                                                                                                       'EXCLUDE'],
                                                                                                           'default': 'INCLUDE',
                                                                                                           'type': 'str'},
                                                                                       'name': {'required': True,
                                                                                                'type': 'str'},
                                                                                       'notes': {'type': 'str'}},
                                                                           'type': 'list'},
                     'nodeExecutionFilters_MonitoringNodeListExecutionFilter': {'elements': 'dict',
                                                                                'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                            'INCLUDE',
                                                                                                                            'EXCLUDE'],
                                                                                                                'default': 'INCLUDE',
                                                                                                                'type': 'str'},
                                                                                            'name': {'required': True,
                                                                                                     'type': 'str'},
                                                                                            'nodes': {'type': 'list'}},
                                                                                'type': 'list'},
                     'nodeExecutionFilters_MonitoringOverlayListExecutionFilter': {'elements': 'dict',
                                                                                   'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                               'INCLUDE',
                                                                                                                               'EXCLUDE'],
                                                                                                                   'default': 'INCLUDE',
                                                                                                                   'type': 'str'},
                                                                                               'name': {'required': True,
                                                                                                        'type': 'str'},
                                                                                               'overlays': {'type': 'list'}},
                                                                                   'type': 'list'},
                     'nodeExecutionFilters_MonitoringResourceExecutionFilter': {'elements': 'dict',
                                                                                'options': {'filterOperation': {'choices': ['NONE',
                                                                                                                            'INCLUDE',
                                                                                                                            'EXCLUDE'],
                                                                                                                'default': 'INCLUDE',
                                                                                                                'type': 'str'},
                                                                                            'name': {'required': True,
                                                                                                     'type': 'str'},
                                                                                            'op': {'choices': ['OR',
                                                                                                               'AND'],
                                                                                                   'default': 'OR',
                                                                                                   'type': 'str'},
                                                                                            'resources': {'type': 'list'}},
                                                                                'type': 'list'},
                     'nodeExecutionFilters_MonitoringTypeExecutionFilter': {'elements': 'dict',
                                                                            'options': {'cloudNode': {'default': False,
                                                                                                      'type': 'bool'},
                                                                                        'dpuNode': {'default': False,
                                                                                                    'type': 'bool'},
                                                                                        'filterOperation': {'choices': ['NONE',
                                                                                                                        'INCLUDE',
                                                                                                                        'EXCLUDE'],
                                                                                                            'default': 'INCLUDE',
                                                                                                            'type': 'str'},
                                                                                        'headNode': {'default': False,
                                                                                                     'type': 'bool'},
                                                                                        'liteNode': {'default': False,
                                                                                                     'type': 'bool'},
                                                                                        'name': {'required': True,
                                                                                                 'type': 'str'},
                                                                                        'physicalNode': {'default': False,
                                                                                                         'type': 'bool'}},
                                                                            'type': 'list'},
                     'notes': {'type': 'str'},
                     'offset': {'default': 0.0, 'type': 'float'},
                     'postJob': {'default': False, 'type': 'bool'},
                     'preJob': {'default': False, 'type': 'bool'},
                     'startupDelay': {'default': 0.0, 'type': 'float'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'suppressedByGoingDown': {'default': False, 'type': 'bool'},
                     'when': {'choices': ['TIMED', 'ONDEMAND', 'OOB', 'ONSTART'],
                              'default': 'TIMED',
                              'type': 'str'}}