#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class PbsProWlmCluster_ArgSpec:
    argument_spec = {'accounting': {'options': {'extractAccountingInfo': {'default': True,
                                                                          'type': 'bool'},
                                                'jobCommentLabels': {'type': 'list'},
                                                'managedHierarchy': {'type': 'list'},
                                                'separator': {'default': '_', 'type': 'str'}},
                                    'type': 'dict'},
                     'cgroups': {'options': {'cgroupPrefix': {'default': 'pbspro', 'type': 'str'},
                                             'cpuacctEnabled': {'default': True, 'type': 'bool'},
                                             'cpusetEnabled': {'default': True, 'type': 'bool'},
                                             'devicesAllow': {'default': ['b *:* rwm', 'c *:* rwm'],
                                                              'type': 'list'},
                                             'devicesEnabled': {'default': True, 'type': 'bool'},
                                             'enabled': {'default': True, 'type': 'bool'},
                                             'hugetlbDefault': {'default': 0, 'type': 'int'},
                                             'hugetlbEnabled': {'default': False, 'type': 'bool'},
                                             'hugetlbReserveAmount': {'default': 0, 'type': 'int'},
                                             'hugetlbReservePercent': {'default': 0, 'type': 'int'},
                                             'jobCgroupTemplate': {'default': 'pbspro.slice/pbspro-$ESCAPE_JOBID.slice',
                                                                   'type': 'str'},
                                             'jobCgroupV2Template': {'default': '$CGROUP_PREFIX.service/jobs/$PBS_CGROUPV2_JOBID',
                                                                     'type': 'str'},
                                             'killTimeout': {'default': 10, 'type': 'int'},
                                             'memoryDefault': {'default': 268435456, 'type': 'int'},
                                             'memoryEnabled': {'default': True, 'type': 'bool'},
                                             'memoryReserveAmount': {'default': 67108864,
                                                                     'type': 'int'},
                                             'memoryReservePercent': {'default': 0, 'type': 'int'},
                                             'memorySoftLimit': {'default': True, 'type': 'bool'},
                                             'memswDefault': {'default': 268435456, 'type': 'int'},
                                             'memswEnabled': {'default': False, 'type': 'bool'},
                                             'memswReserveAmount': {'default': 67108864,
                                                                    'type': 'int'},
                                             'memswReservePercent': {'default': 0, 'type': 'int'},
                                             'mountPoint': {'default': '/sys/fs/cgroup',
                                                            'type': 'str'},
                                             'ncpusAreCores': {'default': False, 'type': 'bool'},
                                             'serverTimeout': {'default': 15, 'type': 'int'},
                                             'useHyperthreads': {'default': False, 'type': 'bool'}},
                                 'type': 'dict'},
                     'cloneFrom': {'default': '', 'type': 'str'},
                     'enableJobHistory': {'default': True, 'type': 'bool'},
                     'enablePostJob': {'default': False, 'type': 'bool'},
                     'enablePreJob': {'default': False, 'type': 'bool'},
                     'flatUid': {'default': True, 'type': 'bool'},
                     'jobHistoryDuration': {'default': '00:30:00', 'type': 'str'},
                     'maxRunning': {'default': 0, 'type': 'int'},
                     'moduleFileTemplate': {'type': 'str'},
                     'name': {'required': True, 'type': 'str'},
                     'network': {'type': 'str'},
                     'pelogs': {'elements': 'dict',
                                'options': {'alarm': {'default': 300, 'type': 'int'},
                                            'debug': {'default': False, 'type': 'bool'},
                                            'defaultAction': {'choices': ['RERUN', 'DELETE'],
                                                              'default': 'RERUN',
                                                              'type': 'str'},
                                            'enableParallel': {'default': True, 'type': 'bool'},
                                            'enabled': {'default': True, 'type': 'bool'},
                                            'events': {'type': 'list'},
                                            'name': {'type': 'str'},
                                            'order': {'default': 0, 'type': 'int'},
                                            'path': {'type': 'str'},
                                            'torqueCompatible': {'default': False, 'type': 'bool'},
                                            'verboseUserOutput': {'default': False,
                                                                  'type': 'bool'}},
                                'type': 'list'},
                     'placeholders': {'elements': 'dict',
                                      'options': {'baseNodeName': {'default': 'placeholder',
                                                                   'type': 'str'},
                                                  'maxNodes': {'default': 0, 'type': 'int'},
                                                  'queue': {'type': 'str'},
                                                  'templateNode': {'type': 'str'}},
                                      'type': 'list'},
                     'prefix': {'type': 'str'},
                     'primaryServer': {'type': 'str'},
                     'spool': {'type': 'str'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'subType': {'choices': ['PBSPRO', 'OPENPBS'],
                                 'default': 'PBSPRO',
                                 'type': 'str'},
                     'tracingJobs': {'type': 'list'},
                     'version': {'choices': ['20', '21', '22', '22.05', '23.06', '24', '25'],
                                 'type': 'str'}}