#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

class SlurmWlmCluster_ArgSpec:
    argument_spec = {'accounting': {'options': {'extractAccountingInfo': {'default': True,
                                                                          'type': 'bool'},
                                                'jobCommentLabels': {'type': 'list'},
                                                'managedHierarchy': {'type': 'list'},
                                                'separator': {'default': '_', 'type': 'str'}},
                                    'type': 'dict'},
                     'accountingStorageTRES': {'default': ['gres/gpu'], 'type': 'list'},
                     'accountingStoreFlags': {'default': ['job_comment'], 'type': 'list'},
                     'autoDetect': {'choices': ['NONE',
                                                'OFF',
                                                'NVML',
                                                'RSMI',
                                                'ONEAPI',
                                                'BCM',
                                                'NRT',
                                                'NVIDIA'],
                                    'default': 'NONE',
                                    'type': 'str'},
                     'batchStartTimeout': {'default': 0, 'type': 'int'},
                     'bcmManagedParameters': {'default': ['AccountingStorageBackupHost',
                                                          'AccountingStorageHost',
                                                          'AccountingStorageTRES',
                                                          'AccountingStoreFlags',
                                                          'BatchStartTimeout',
                                                          'ClusterName',
                                                          'Epilog',
                                                          'EpilogSlurmctld',
                                                          'GresTypes',
                                                          'Licenses',
                                                          'Prolog',
                                                          'PrologEpilogTimeout',
                                                          'PrologFlags',
                                                          'PrologSlurmctld',
                                                          'ResumeProgram',
                                                          'ResumeTimeout',
                                                          'SchedulerParameters',
                                                          'SchedulerType',
                                                          'SelectType',
                                                          'SelectTypeParameters',
                                                          'SlurmctldAddr',
                                                          'SlurmctldHost',
                                                          'SlurmctldParameters',
                                                          'SlurmdParameters',
                                                          'SrunEpilog',
                                                          'SrunProlog',
                                                          'StateSaveLocation',
                                                          'SuspendProgram',
                                                          'SuspendTime',
                                                          'SuspendTimeout',
                                                          'TaskEpilog',
                                                          'TaskProlog',
                                                          'TopologyParam',
                                                          'TopologyPlugin'],
                                              'type': 'list'},
                     'cgroupPlugin': {'choices': ['CGROUPV1', 'CGROUPV2', 'AUTODETECT', 'DISABLED'],
                                      'default': 'AUTODETECT',
                                      'type': 'str'},
                     'cgroups': {'options': {'allowedRamSpace': {'default': 1, 'type': 'float'},
                                             'allowedSwapSpace': {'default': 0, 'type': 'float'},
                                             'constrainCores': {'default': False, 'type': 'bool'},
                                             'constrainDevices': {'default': False, 'type': 'bool'},
                                             'constrainRAMSpace': {'default': False,
                                                                   'type': 'bool'},
                                             'constrainSwapSpace': {'default': False,
                                                                    'type': 'bool'},
                                             'jobCgroupTemplate': {'default': 'slurm/uid_$UID/job_$JOBID',
                                                                   'type': 'str'},
                                             'jobCgroupV2Template': {'default': 'system.slice/slurmstepd.scope/job_$JOBID',
                                                                     'type': 'str'},
                                             'maxRAM': {'default': 1, 'type': 'float'},
                                             'maxSwap': {'default': 1, 'type': 'float'},
                                             'memorySwappiness': {'default': 1, 'type': 'float'},
                                             'minRAMSpace': {'default': 31457280, 'type': 'int'},
                                             'mountPoint': {'default': '/sys/fs/cgroup',
                                                            'type': 'str'}},
                                 'type': 'dict'},
                     'cloneFrom': {'default': '', 'type': 'str'},
                     'configureMigs': {'default': True, 'type': 'bool'},
                     'drainReasonPolicy': {'choices': ['REPLACE', 'APPEND', 'SKIP'],
                                           'default': 'REPLACE',
                                           'type': 'str'},
                     'enablePostJob': {'default': False, 'type': 'bool'},
                     'enablePreJob': {'default': False, 'type': 'bool'},
                     'epilog': {'default': '/cm/local/apps/cmd/scripts/epilog', 'type': 'str'},
                     'epilogSlurmctld': {'type': 'str'},
                     'etc': {'type': 'str'},
                     'gresConfFileTemplate': {'type': 'str'},
                     'gresTypes': {'default': ['gpu'], 'type': 'list'},
                     'licenses': {'elements': 'dict',
                                  'options': {'count': {'default': 0, 'type': 'int'},
                                              'name': {'required': True, 'type': 'str'}},
                                  'type': 'list'},
                     'moduleFileTemplate': {'type': 'str'},
                     'name': {'required': True, 'type': 'str'},
                     'network': {'type': 'str'},
                     'ociSettings': {'options': {'containerPath': {'type': 'str'},
                                                 'createEnvFile': {'default': False,
                                                                   'type': 'bool'},
                                                 'runTimeCreate': {'type': 'str'},
                                                 'runTimeDelete': {'type': 'str'},
                                                 'runTimeKill': {'type': 'str'},
                                                 'runTimeQuery': {'type': 'str'},
                                                 'runTimeRun': {'type': 'str'},
                                                 'runTimeStart': {'type': 'str'}},
                                     'type': 'dict'},
                     'placeholders': {'elements': 'dict',
                                      'options': {'baseNodeName': {'default': 'placeholder',
                                                                   'type': 'str'},
                                                  'maxNodes': {'default': 0, 'type': 'int'},
                                                  'queue': {'type': 'str'},
                                                  'templateNode': {'type': 'str'}},
                                      'type': 'list'},
                     'powerSavingEnabled': {'default': False, 'type': 'bool'},
                     'prefix': {'type': 'str'},
                     'primaryServer': {'type': 'str'},
                     'prolog': {'default': '/cm/local/apps/cmd/scripts/prolog', 'type': 'str'},
                     'prologEpilogTimeout': {'default': 0, 'type': 'int'},
                     'prologFlags': {'default': ['Alloc'], 'type': 'list'},
                     'prologSlurmctld': {'type': 'str'},
                     'prsSettings': {'options': {'certificatePath': {'default': '/cm/local/apps/prs/etc/${WLM_NAME}.pem',
                                                                     'type': 'str'},
                                                 'privateKeyPath': {'default': '/cm/local/apps/prs/etc/${WLM_NAME}.key',
                                                                    'type': 'str'}},
                                     'type': 'dict'},
                     'resumeProgram': {'default': '/cm/local/apps/slurm/current/scripts/power/poweron',
                                       'type': 'str'},
                     'resumeTimeout': {'default': 60, 'type': 'int'},
                     'scheduler': {'choices': ['backfill', 'builtin'],
                                   'default': 'backfill',
                                   'type': 'str'},
                     'schedulerParameters': {'type': 'list'},
                     'selectType': {'default': 'select/cons_tres', 'type': 'str'},
                     'selectTypeParameters': {'default': ['CR_Core'], 'type': 'list'},
                     'slurmConfFileTemplate': {'type': 'str'},
                     'slurmctldParameters': {'type': 'list'},
                     'slurmdParameters': {'type': 'list'},
                     'srunEpilog': {'type': 'str'},
                     'srunProlog': {'type': 'str'},
                     'state': {'choices': ['present', 'absent'],
                               'default': 'present',
                               'type': 'str'},
                     'stateSave': {'type': 'str'},
                     'suspendProgram': {'default': '/cm/local/apps/slurm/current/scripts/power/poweroff',
                                        'type': 'str'},
                     'suspendTime': {'default': 300, 'type': 'int'},
                     'suspendTimeout': {'default': 30, 'type': 'int'},
                     'taskEpilog': {'type': 'str'},
                     'taskProlog': {'type': 'str'},
                     'topologySettings': {'options': {'blockSettings': {'options': {'allowedNodeGroups': {'type': 'list'},
                                                                                    'allowedRacks': {'type': 'list'},
                                                                                    'blockEntity': {'choices': ['RACK',
                                                                                                                'NODEGROUP'],
                                                                                                    'default': 'RACK',
                                                                                                    'type': 'str'},
                                                                                    'blockSizes': {'type': 'list'}},
                                                                        'type': 'dict'},
                                                      'params': {'options': {'dragonfly': {'default': False,
                                                                                           'type': 'bool'},
                                                                             'routePart': {'default': False,
                                                                                           'type': 'bool'},
                                                                             'routeTree': {'default': False,
                                                                                           'type': 'bool'},
                                                                             'switchAsNodeRank': {'default': False,
                                                                                                  'type': 'bool'},
                                                                             'topoOptional': {'default': False,
                                                                                              'type': 'bool'}},
                                                                 'type': 'dict'},
                                                      'topographSettings': {'options': {'configPath': {'default': '/etc/topograph/topograph-config.yaml',
                                                                                                       'type': 'str'},
                                                                                        'fetchAttempts': {'default': 12,
                                                                                                          'type': 'int'},
                                                                                        'fetchTimeout': {'default': 20,
                                                                                                         'type': 'int'},
                                                                                        'fetchWaitTime': {'default': 15,
                                                                                                          'type': 'int'},
                                                                                        'hostname': {'default': 'localhost',
                                                                                                     'type': 'str'},
                                                                                        'httpParameters': {'type': 'str'},
                                                                                        'passCloudCredentials': {'default': False,
                                                                                                                 'type': 'bool'}},
                                                                            'type': 'dict'},
                                                      'topologyPlugin': {'choices': ['NONE',
                                                                                     'DEFAULT',
                                                                                     'TREE',
                                                                                     'BLOCK',
                                                                                     'TORUS'],
                                                                         'default': 'NONE',
                                                                         'type': 'str'},
                                                      'topologySource': {'choices': ['NONE',
                                                                                     'INTERNAL',
                                                                                     'TOPOGRAPH'],
                                                                         'default': 'NONE',
                                                                         'type': 'str'},
                                                      'treeSettings': {'options': {'topologyEphemeralSwitches': {'default': True,
                                                                                                                 'type': 'bool'},
                                                                                   'topologySwitches': {'type': 'list'}},
                                                                       'type': 'dict'}},
                                          'type': 'dict'},
                     'tracingJobs': {'type': 'list'},
                     'version': {'choices': ['24.05',
                                             '24.05-sharp',
                                             '24.11',
                                             '24.11-sharp',
                                             '25.05',
                                             '25.05-sharp'],
                                 'type': 'str'}}