---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: test-ocp
rendezvousIP: 10.141.160.50
bootArtifactsBaseURL: http://10.141.255.254:8080/tftpboot/repos/openshift-4.20/
hosts:
  - hostname: ocp-master-0
    role: master
    interfaces:
      - name: enp1s0
        macAddress: 52:54:00:0C:01:00
    networkConfig:
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          ipv4:
            enabled: true
            address:
              - ip: 10.141.160.50
                prefix-length: 16
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.141.255.254
            next-hop-interface: enp1s0
  - hostname: ocp-master-1
    role: master
    interfaces:
      - name: enp1s0
        macAddress: 52:54:00:0C:01:01
    networkConfig:
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          ipv4:
            enabled: true
            address:
              - ip: 10.141.160.51
                prefix-length: 16
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.141.255.254
            next-hop-interface: enp1s0
  - hostname: ocp-master-2
    role: master
    interfaces:
      - name: enp1s0
        macAddress: 52:54:00:0C:01:02
    networkConfig:
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          ipv4:
            enabled: true
            address:
              - ip: 10.141.160.52
                prefix-length: 16
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.141.255.254
            next-hop-interface: enp1s0
