---
- name: Mount pseudo filesystems under {{ software_image_root_dir }}/{{ software_image.name }}
  ansible.posix.mount:
    path: "{{ software_image_root_dir }}/{{ software_image.name }}{{ mount }}"
    src: "{{ mount }}"
    opts: bind
    state: mounted
    fstype: none
    fstab: /etc/fstab.{{ software_image.name }}
  loop:
    - /dev
    - /proc
    - /sys
  loop_control:
    loop_var: mount

- name: Ensure pseudo systemd-resolvconf run directory exists in chroot
  file:
    path: "{{ software_image_root_dir }}/{{ software_image.name }}/run/systemd/resolve"
    state: directory

- name: Copy host's resolv.conf to chroot
  when: not ansible_check_mode
  copy:
    src: /etc/resolv.conf
    dest: "{{ software_image_root_dir }}/{{ software_image.name }}/run/systemd/resolve/resolv.conf"
    remote_src: true

# not supported on c8u4,s12sp5,s15sp2,rhel8u4
# - name: Bind SSH port {{ software_image.tunnel }} to chroot {{ software_image_root_dir }}/{{ software_image.name }}
#   copy:
#     dest: /etc/ssh/sshd_config.d/brightcomputing.bcm.software_image_tunnel.{{ software_image.name }}
#     content: |
#       Port {{ software_image.tunnel }}
#       Match LocalPort {{ software_image.tunnel }}
#         ChrootDirectory {{ software_image_root_dir }}/{{ software_image.name }}
#         X11Forwarding no
#   notify:
#     - Restart ssh

- name: Listen on SSH port {{ software_image.tunnel }}
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} BRIGHTCOMPUTING.BCM.SOFTWARE_IMAGE_TUNNEL:{{ software_image.name }}.listen ANSIBLE MANAGED BLOCK"
    marker_end: 'END  '
    insertbefore: BOF
    state: present
    block: |
      Port {{ software_image.tunnel }}
  notify:
    - Restart ssh

- name: Bind SSH port {{ software_image.tunnel }} to chroot /cm/images/{{ software_image.name }}
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} BRIGHTCOMPUTING.BCM.SOFTWARE_IMAGE_TUNNEL:{{ software_image.name }}.chroot ANSIBLE MANAGED BLOCK"
    marker_end: 'END  '
    insertafter: EOF
    state: present
    block: |
      Match LocalPort {{ software_image.tunnel }}
        ChrootDirectory /cm/images/{{ software_image.name }}
        X11Forwarding no
  notify:
    - Restart ssh